// RUN: triton-xyz-opt --split-input-file --tta-normalize --tta-to-memref --canonicalize --cse %s | FileCheck %s

module {
// CHECK-LABEL:   tt.func @structured_basic(
// CHECK-SAME:      %[[ARG0:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG1:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>) {
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:           %[[ALLOC_0:.*]] = memref.alloc() : memref<4xf32>
// CHECK:           %[[REINTERPRET_CAST_0:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_0]] to offset: [0], sizes: [4], strides: [1] : memref<*xf32> to memref<4xf32, strided<[1]>>
// CHECK:           memref.copy %[[REINTERPRET_CAST_0]], %[[ALLOC_0]] : memref<4xf32, strided<[1]>> to memref<4xf32>
// CHECK:           %[[TO_TENSOR_0:.*]] = bufferization.to_tensor %[[ALLOC_0]] restrict writable : memref<4xf32> to tensor<4xf32>
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_1:.*]] = builtin.unrealized_conversion_cast %[[ARG1]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:           %[[REINTERPRET_CAST_1:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_1]] to offset: [0], sizes: [4], strides: [1] : memref<*xf32> to memref<4xf32, strided<[1]>>
// CHECK:           bufferization.materialize_in_destination %[[TO_TENSOR_0]] in writable %[[REINTERPRET_CAST_1]] : (tensor<4xf32>, memref<4xf32, strided<[1]>>) -> ()
// CHECK:           tt.return
// CHECK:         }
  tt.func @structured_basic(%src: !tt.ptr<f32>, %dst: !tt.ptr<f32>) {
    %src_addr = tta.make_addr %src to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
    %val = "tta.load"(%src_addr) <{operandSegmentSizes = array<i32: 1, 0, 0>, static_mask_dims = array<i64>}> : (!tta.addr<f32, 1, 1>) -> tensor<4xf32>
    %dst_addr = tta.make_addr %dst to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
    "tta.store"(%dst_addr, %val) <{static_mask_dims = array<i64>}> : (!tta.addr<f32, 1, 1>, tensor<4xf32>) -> ()
    tt.return
  }
}

// -----

module {
// CHECK-LABEL:   tt.func @block_ptr_with_advance(
// CHECK-SAME:      %[[ARG0:[-0-9A-Za-z$._]+]]: !tt.ptr<f16>) {
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<f16> to memref<*xf16>
// CHECK:           %[[ALLOC_0:.*]] = memref.alloc() : memref<4x4xf16>
// CHECK:           %[[REINTERPRET_CAST_0:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_0]] to offset: [1], sizes: [4, 4], strides: [4, 1] : memref<*xf16> to memref<4x4xf16, strided<[4, 1], offset: 1>>
// CHECK:           memref.copy %[[REINTERPRET_CAST_0]], %[[ALLOC_0]] : memref<4x4xf16, strided<[4, 1], offset: 1>> to memref<4x4xf16>
// CHECK:           %[[TO_TENSOR_0:.*]] = bufferization.to_tensor %[[ALLOC_0]] restrict writable : memref<4x4xf16> to tensor<4x4xf16>
// CHECK:           %[[REINTERPRET_CAST_1:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_0]] to offset: [0], sizes: [4, 4], strides: [4, 1] : memref<*xf16> to memref<4x4xf16, strided<[4, 1]>>
// CHECK:           bufferization.materialize_in_destination %[[TO_TENSOR_0]] in writable %[[REINTERPRET_CAST_1]] : (tensor<4x4xf16>, memref<4x4xf16, strided<[4, 1]>>) -> ()
// CHECK:           tt.return
// CHECK:         }
  tt.func @block_ptr_with_advance(%base: !tt.ptr<f16>) {
    %addr = tta.make_addr %base to sizes: [4, 4], strides: [4, 1], offsets: [0, 0], wrap_boundaries: [0, 0], layout: "block", parent_shape: [4, 4] {layout_payload = {order = array<i32: 1, 0>}} : <f16> to !tta.addr<f16, 2, 1>
    %next = "tta.advance"(%addr) <{static_deltas = array<i64: 0, 1>}> : (!tta.addr<f16, 2, 1>) -> !tta.addr<f16, 2, 1>
    %val = "tta.load"(%next) <{operandSegmentSizes = array<i32: 1, 0, 0>, static_mask_dims = array<i64>}> : (!tta.addr<f16, 2, 1>) -> tensor<4x4xf16>
    "tta.store"(%addr, %val) <{static_mask_dims = array<i64>}> : (!tta.addr<f16, 2, 1>, tensor<4x4xf16>) -> ()
    tt.return
  }
}

// -----

module {
// CHECK-LABEL:   tt.func @indirect_masked_load_store(
// CHECK-SAME:      %[[ARG0:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG1:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant dense<[0, 1, 2, 3]> : tensor<4xindex>
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 1 : index
// CHECK:           %[[CONSTANT_2:.*]] = arith.constant 0 : index
// CHECK:           %[[CONSTANT_3:.*]] = arith.constant 4 : index
// CHECK:           %[[CONSTANT_4:.*]] = arith.constant dense<[true, false, true, false]> : tensor<4xi1>
// CHECK:           %[[CONSTANT_5:.*]] = arith.constant 1.250000e+00 : f32
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:           %[[ALLOC_0:.*]] = memref.alloc() : memref<4xf32>
// CHECK:           linalg.fill ins(%[[CONSTANT_5]] : f32) outs(%[[ALLOC_0]] : memref<4xf32>)
// CHECK:           scf.for %[[VAL_0:.*]] = %[[CONSTANT_2]] to %[[CONSTANT_3]] step %[[CONSTANT_1]] {
// CHECK:             %[[EXTRACT_0:.*]] = tensor.extract %[[CONSTANT_4]]{{\[}}%[[VAL_0]]] : tensor<4xi1>
// CHECK:             scf.if %[[EXTRACT_0]] {
// CHECK:               %[[EXTRACT_1:.*]] = tensor.extract %[[CONSTANT_0]]{{\[}}%[[VAL_0]]] : tensor<4xindex>
// CHECK:               %[[REINTERPRET_CAST_0:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_0]] to offset: {{\[}}%[[EXTRACT_1]]], sizes: [1], strides: [1] : memref<*xf32> to memref<1xf32, strided<[1], offset: ?>>
// CHECK:               %[[SUBVIEW_0:.*]] = memref.subview %[[ALLOC_0]]{{\[}}%[[VAL_0]]] [1] [1] : memref<4xf32> to memref<1xf32, strided<[1], offset: ?>>
// CHECK:               memref.copy %[[REINTERPRET_CAST_0]], %[[SUBVIEW_0]] : memref<1xf32, strided<[1], offset: ?>> to memref<1xf32, strided<[1], offset: ?>>
// CHECK:             }
// CHECK:           }
// CHECK:           %[[TO_TENSOR_0:.*]] = bufferization.to_tensor %[[ALLOC_0]] restrict writable : memref<4xf32> to tensor<4xf32>
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_1:.*]] = builtin.unrealized_conversion_cast %[[ARG1]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:           scf.for %[[VAL_1:.*]] = %[[CONSTANT_2]] to %[[CONSTANT_3]] step %[[CONSTANT_1]] {
// CHECK:             %[[EXTRACT_2:.*]] = tensor.extract %[[CONSTANT_4]]{{\[}}%[[VAL_1]]] : tensor<4xi1>
// CHECK:             scf.if %[[EXTRACT_2]] {
// CHECK:               %[[EXTRACT_3:.*]] = tensor.extract %[[CONSTANT_0]]{{\[}}%[[VAL_1]]] : tensor<4xindex>
// CHECK:               %[[REINTERPRET_CAST_1:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_1]] to offset: {{\[}}%[[EXTRACT_3]]], sizes: [1], strides: [1] : memref<*xf32> to memref<1xf32, strided<[1], offset: ?>>
// CHECK:               %[[EXTRACT_SLICE_0:.*]] = tensor.extract_slice %[[TO_TENSOR_0]]{{\[}}%[[VAL_1]]] [1] [1] : tensor<4xf32> to tensor<1xf32>
// CHECK:               bufferization.materialize_in_destination %[[EXTRACT_SLICE_0]] in writable %[[REINTERPRET_CAST_1]] : (tensor<1xf32>, memref<1xf32, strided<[1], offset: ?>>) -> ()
// CHECK:             }
// CHECK:           }
// CHECK:           tt.return
// CHECK:         }
  tt.func @indirect_masked_load_store(%src: !tt.ptr<f32>, %dst: !tt.ptr<f32>) {
    %offsets = arith.constant dense<[0, 1, 2, 3]> : tensor<4xi32>
    %mask = arith.constant dense<[true, false, true, false]> : tensor<4xi1>
    %other = arith.constant 1.250000e+00 : f32

    %src_addr = tta.make_addr %src to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
    %src_idx = "tta.indirect_reindex"(%src_addr, %offsets, %mask) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 1, 1>, tensor<4xi32>, tensor<4xi1>) -> !tta.addr<f32, 1, 1>
    %val = "tta.load"(%src_idx, %other) <{operandSegmentSizes = array<i32: 1, 0, 1>, static_mask_dims = array<i64>}> : (!tta.addr<f32, 1, 1>, f32) -> tensor<4xf32>

    %dst_addr = tta.make_addr %dst to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
    %dst_idx = "tta.indirect_reindex"(%dst_addr, %offsets, %mask) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 1, 1>, tensor<4xi32>, tensor<4xi1>) -> !tta.addr<f32, 1, 1>
    "tta.store"(%dst_idx, %val) <{static_mask_dims = array<i64>}> : (!tta.addr<f32, 1, 1>, tensor<4xf32>) -> ()
    tt.return
  }
}

// -----

module {
// CHECK-LABEL:   tt.func @indirect_reindex_load_store(
// CHECK-SAME:      %[[ARG0:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG1:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant dense<[0, 1, 2, 3]> : tensor<4xindex>
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 1 : index
// CHECK:           %[[CONSTANT_2:.*]] = arith.constant 0 : index
// CHECK:           %[[CONSTANT_3:.*]] = arith.constant 4 : index
// CHECK:           %[[CONSTANT_4:.*]] = arith.constant dense<[true, false, true, false]> : tensor<4xi1>
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:           %[[ALLOC_0:.*]] = memref.alloc() : memref<4xf32>
// CHECK:           scf.for %[[VAL_0:.*]] = %[[CONSTANT_2]] to %[[CONSTANT_3]] step %[[CONSTANT_1]] {
// CHECK:             %[[EXTRACT_0:.*]] = tensor.extract %[[CONSTANT_4]]{{\[}}%[[VAL_0]]] : tensor<4xi1>
// CHECK:             scf.if %[[EXTRACT_0]] {
// CHECK:               %[[EXTRACT_1:.*]] = tensor.extract %[[CONSTANT_0]]{{\[}}%[[VAL_0]]] : tensor<4xindex>
// CHECK:               %[[REINTERPRET_CAST_0:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_0]] to offset: {{\[}}%[[EXTRACT_1]]], sizes: [1], strides: [1] : memref<*xf32> to memref<1xf32, strided<[1], offset: ?>>
// CHECK:               %[[SUBVIEW_0:.*]] = memref.subview %[[ALLOC_0]]{{\[}}%[[VAL_0]]] [1] [1] : memref<4xf32> to memref<1xf32, strided<[1], offset: ?>>
// CHECK:               memref.copy %[[REINTERPRET_CAST_0]], %[[SUBVIEW_0]] : memref<1xf32, strided<[1], offset: ?>> to memref<1xf32, strided<[1], offset: ?>>
// CHECK:             }
// CHECK:           }
// CHECK:           %[[TO_TENSOR_0:.*]] = bufferization.to_tensor %[[ALLOC_0]] restrict writable : memref<4xf32> to tensor<4xf32>
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_1:.*]] = builtin.unrealized_conversion_cast %[[ARG1]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:           scf.for %[[VAL_1:.*]] = %[[CONSTANT_2]] to %[[CONSTANT_3]] step %[[CONSTANT_1]] {
// CHECK:             %[[EXTRACT_2:.*]] = tensor.extract %[[CONSTANT_4]]{{\[}}%[[VAL_1]]] : tensor<4xi1>
// CHECK:             scf.if %[[EXTRACT_2]] {
// CHECK:               %[[EXTRACT_3:.*]] = tensor.extract %[[CONSTANT_0]]{{\[}}%[[VAL_1]]] : tensor<4xindex>
// CHECK:               %[[REINTERPRET_CAST_1:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_1]] to offset: {{\[}}%[[EXTRACT_3]]], sizes: [1], strides: [1] : memref<*xf32> to memref<1xf32, strided<[1], offset: ?>>
// CHECK:               %[[EXTRACT_SLICE_0:.*]] = tensor.extract_slice %[[TO_TENSOR_0]]{{\[}}%[[VAL_1]]] [1] [1] : tensor<4xf32> to tensor<1xf32>
// CHECK:               bufferization.materialize_in_destination %[[EXTRACT_SLICE_0]] in writable %[[REINTERPRET_CAST_1]] : (tensor<1xf32>, memref<1xf32, strided<[1], offset: ?>>) -> ()
// CHECK:             }
// CHECK:           }
// CHECK:           tt.return
// CHECK:         }
  tt.func @indirect_reindex_load_store(%src: !tt.ptr<f32>, %dst: !tt.ptr<f32>) {
    %offsets = arith.constant dense<[0, 1, 2, 3]> : tensor<4xi32>
    %mask = arith.constant dense<[true, false, true, false]> : tensor<4xi1>

    %src_addr = tta.make_addr %src to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
    %src_idx = "tta.indirect_reindex"(%src_addr, %offsets, %mask) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 1, 1>, tensor<4xi32>, tensor<4xi1>) -> !tta.addr<f32, 1, 1>
    %val = "tta.load"(%src_idx) <{operandSegmentSizes = array<i32: 1, 0, 0>, static_mask_dims = array<i64>}> : (!tta.addr<f32, 1, 1>) -> tensor<4xf32>

    %dst_addr = tta.make_addr %dst to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
    %dst_idx = "tta.indirect_reindex"(%dst_addr, %offsets, %mask) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 1, 1>, tensor<4xi32>, tensor<4xi1>) -> !tta.addr<f32, 1, 1>
    "tta.store"(%dst_idx, %val) <{static_mask_dims = array<i64>}> : (!tta.addr<f32, 1, 1>, tensor<4xf32>) -> ()
    tt.return
  }
}


// -----

module {
// CHECK-LABEL:   tt.func @imported_addr_basic(
// CHECK-SAME:      %[[ARG0:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG1:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>) {
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:           %[[ALLOC_0:.*]] = memref.alloc() : memref<4xf32>
// CHECK:           %[[REINTERPRET_CAST_0:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_0]] to offset: [0], sizes: [4], strides: [1] : memref<*xf32> to memref<4xf32, strided<[1]>>
// CHECK:           memref.copy %[[REINTERPRET_CAST_0]], %[[ALLOC_0]] : memref<4xf32, strided<[1]>> to memref<4xf32>
// CHECK:           %[[TO_TENSOR_0:.*]] = bufferization.to_tensor %[[ALLOC_0]] restrict writable : memref<4xf32> to tensor<4xf32>
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_1:.*]] = builtin.unrealized_conversion_cast %[[ARG1]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:           %[[REINTERPRET_CAST_1:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_1]] to offset: [0], sizes: [4], strides: [1] : memref<*xf32> to memref<4xf32, strided<[1]>>
// CHECK:           bufferization.materialize_in_destination %[[TO_TENSOR_0]] in writable %[[REINTERPRET_CAST_1]] : (tensor<4xf32>, memref<4xf32, strided<[1]>>) -> ()
// CHECK:           tt.return
// CHECK:         }
  tt.func @imported_addr_basic(%src: !tt.ptr<f32>, %dst: !tt.ptr<f32>) {
    %src_addr = tta.make_addr %src to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
    %val = "tta.load"(%src_addr) <{operandSegmentSizes = array<i32: 1, 0, 0>, static_mask_dims = array<i64>}> : (!tta.addr<f32, 1, 1>) -> tensor<4xf32>

    %dst_addr = tta.make_addr %dst to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
    "tta.store"(%dst_addr, %val) <{static_mask_dims = array<i64>}> : (!tta.addr<f32, 1, 1>, tensor<4xf32>) -> ()
    tt.return
  }
}


// -----

module {
// CHECK-LABEL:   tt.func @loop_carried_addr_supported(
// CHECK-SAME:      %[[ARG0:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG1:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG2:[-0-9A-Za-z$._]+]]: i32) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 0 : i32
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 1 : i32
// CHECK:           %[[MAKE_ADDR_0:.*]] = tta.make_addr %[[ARG0]] to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
// CHECK:           %[[MAKE_ADDR_1:.*]] = tta.make_addr %[[ARG1]] to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
// CHECK:           %[[FOR_0:.*]]:2 = scf.for %[[VAL_0:.*]] = %[[CONSTANT_0]] to %[[ARG2]] step %[[CONSTANT_1]] iter_args(%[[VAL_1:.*]] = %[[MAKE_ADDR_0]], %[[VAL_2:.*]] = %[[MAKE_ADDR_1]]) -> (!tta.addr<f32, 1, 1>, !tta.addr<f32, 1, 1>)  : i32 {
// CHECK:             %[[INDEX_CAST_0:.*]] = arith.index_cast %[[VAL_0]] : i32 to index
// CHECK:             %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:             %[[ALLOC_0:.*]] = memref.alloc() : memref<4xf32>
// CHECK:             %[[REINTERPRET_CAST_0:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_0]] to offset: {{\[}}%[[INDEX_CAST_0]]], sizes: [4], strides: [1] : memref<*xf32> to memref<4xf32, strided<[1], offset: ?>>
// CHECK:             memref.copy %[[REINTERPRET_CAST_0]], %[[ALLOC_0]] : memref<4xf32, strided<[1], offset: ?>> to memref<4xf32>
// CHECK:             %[[TO_TENSOR_0:.*]] = bufferization.to_tensor %[[ALLOC_0]] restrict writable : memref<4xf32> to tensor<4xf32>
// CHECK:             %[[UNREALIZED_CONVERSION_CAST_1:.*]] = builtin.unrealized_conversion_cast %[[ARG1]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:             %[[REINTERPRET_CAST_1:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_1]] to offset: {{\[}}%[[INDEX_CAST_0]]], sizes: [4], strides: [1] : memref<*xf32> to memref<4xf32, strided<[1], offset: ?>>
// CHECK:             bufferization.materialize_in_destination %[[TO_TENSOR_0]] in writable %[[REINTERPRET_CAST_1]] : (tensor<4xf32>, memref<4xf32, strided<[1], offset: ?>>) -> ()
// CHECK:             %[[VAL_3:.*]] = "tta.advance"(%[[VAL_1]]) <{static_deltas = array<i64: 1>}> : (!tta.addr<f32, 1, 1>) -> !tta.addr<f32, 1, 1>
// CHECK:             %[[VAL_4:.*]] = "tta.advance"(%[[VAL_2]]) <{static_deltas = array<i64: 1>}> : (!tta.addr<f32, 1, 1>) -> !tta.addr<f32, 1, 1>
// CHECK:             scf.yield %[[VAL_3]], %[[VAL_4]] : !tta.addr<f32, 1, 1>, !tta.addr<f32, 1, 1>
// CHECK:           }
// CHECK:           tt.return
// CHECK:         }
  tt.func @loop_carried_addr_supported(%src: !tt.ptr<f32>, %dst: !tt.ptr<f32>, %n: i32) {
    %c0 = arith.constant 0 : i32
    %c1 = arith.constant 1 : i32
    %src_addr0 = tta.make_addr %src to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
    %dst_addr0 = tta.make_addr %dst to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
    %res:2 = scf.for %iv = %c0 to %n step %c1 iter_args(%src_addr = %src_addr0, %dst_addr = %dst_addr0) -> (!tta.addr<f32, 1, 1>, !tta.addr<f32, 1, 1>) : i32 {
      %val = "tta.load"(%src_addr) <{operandSegmentSizes = array<i32: 1, 0, 0>, static_mask_dims = array<i64>}> : (!tta.addr<f32, 1, 1>) -> tensor<4xf32>
      "tta.store"(%dst_addr, %val) <{static_mask_dims = array<i64>}> : (!tta.addr<f32, 1, 1>, tensor<4xf32>) -> ()
      %next_src = "tta.advance"(%src_addr) <{static_deltas = array<i64: 1>}> : (!tta.addr<f32, 1, 1>) -> !tta.addr<f32, 1, 1>
      %next_dst = "tta.advance"(%dst_addr) <{static_deltas = array<i64: 1>}> : (!tta.addr<f32, 1, 1>) -> !tta.addr<f32, 1, 1>
      scf.yield %next_src, %next_dst : !tta.addr<f32, 1, 1>, !tta.addr<f32, 1, 1>
    }
    tt.return
  }
}


// -----

module {
// CHECK-LABEL:   tt.func @loop_carried_addr_supported_non_unit(
// CHECK-SAME:      %[[ARG0:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG1:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG2:[-0-9A-Za-z$._]+]]: i32) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 3 : i32
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 2 : i32
// CHECK:           %[[MAKE_ADDR_0:.*]] = tta.make_addr %[[ARG0]] to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
// CHECK:           %[[MAKE_ADDR_1:.*]] = tta.make_addr %[[ARG1]] to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
// CHECK:           %[[FOR_0:.*]]:2 = scf.for %[[VAL_0:.*]] = %[[CONSTANT_0]] to %[[ARG2]] step %[[CONSTANT_1]] iter_args(%[[VAL_1:.*]] = %[[MAKE_ADDR_0]], %[[VAL_2:.*]] = %[[MAKE_ADDR_1]]) -> (!tta.addr<f32, 1, 1>, !tta.addr<f32, 1, 1>)  : i32 {
// CHECK:             %[[SUBI_0:.*]] = arith.subi %[[VAL_0]], %[[CONSTANT_0]] : i32
// CHECK:             %[[DIVSI_0:.*]] = arith.divsi %[[SUBI_0]], %[[CONSTANT_1]] : i32
// CHECK:             %[[INDEX_CAST_0:.*]] = arith.index_cast %[[DIVSI_0]] : i32 to index
// CHECK:             %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:             %[[ALLOC_0:.*]] = memref.alloc() : memref<4xf32>
// CHECK:             %[[REINTERPRET_CAST_0:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_0]] to offset: {{\[}}%[[INDEX_CAST_0]]], sizes: [4], strides: [1] : memref<*xf32> to memref<4xf32, strided<[1], offset: ?>>
// CHECK:             memref.copy %[[REINTERPRET_CAST_0]], %[[ALLOC_0]] : memref<4xf32, strided<[1], offset: ?>> to memref<4xf32>
// CHECK:             %[[TO_TENSOR_0:.*]] = bufferization.to_tensor %[[ALLOC_0]] restrict writable : memref<4xf32> to tensor<4xf32>
// CHECK:             %[[UNREALIZED_CONVERSION_CAST_1:.*]] = builtin.unrealized_conversion_cast %[[ARG1]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:             %[[REINTERPRET_CAST_1:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_1]] to offset: {{\[}}%[[INDEX_CAST_0]]], sizes: [4], strides: [1] : memref<*xf32> to memref<4xf32, strided<[1], offset: ?>>
// CHECK:             bufferization.materialize_in_destination %[[TO_TENSOR_0]] in writable %[[REINTERPRET_CAST_1]] : (tensor<4xf32>, memref<4xf32, strided<[1], offset: ?>>) -> ()
// CHECK:             %[[VAL_3:.*]] = "tta.advance"(%[[VAL_1]]) <{static_deltas = array<i64: 1>}> : (!tta.addr<f32, 1, 1>) -> !tta.addr<f32, 1, 1>
// CHECK:             %[[VAL_4:.*]] = "tta.advance"(%[[VAL_2]]) <{static_deltas = array<i64: 1>}> : (!tta.addr<f32, 1, 1>) -> !tta.addr<f32, 1, 1>
// CHECK:             scf.yield %[[VAL_3]], %[[VAL_4]] : !tta.addr<f32, 1, 1>, !tta.addr<f32, 1, 1>
// CHECK:           }
// CHECK:           tt.return
// CHECK:         }
  tt.func @loop_carried_addr_supported_non_unit(%src: !tt.ptr<f32>, %dst: !tt.ptr<f32>, %n: i32) {
    %c3 = arith.constant 3 : i32
    %c2 = arith.constant 2 : i32
    %src_addr0 = tta.make_addr %src to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
    %dst_addr0 = tta.make_addr %dst to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
    %res:2 = scf.for %iv = %c3 to %n step %c2 iter_args(%src_addr = %src_addr0, %dst_addr = %dst_addr0) -> (!tta.addr<f32, 1, 1>, !tta.addr<f32, 1, 1>) : i32 {
      %val = "tta.load"(%src_addr) <{operandSegmentSizes = array<i32: 1, 0, 0>, static_mask_dims = array<i64>}> : (!tta.addr<f32, 1, 1>) -> tensor<4xf32>
      "tta.store"(%dst_addr, %val) <{static_mask_dims = array<i64>}> : (!tta.addr<f32, 1, 1>, tensor<4xf32>) -> ()
      %next_src = "tta.advance"(%src_addr) <{static_deltas = array<i64: 1>}> : (!tta.addr<f32, 1, 1>) -> !tta.addr<f32, 1, 1>
      %next_dst = "tta.advance"(%dst_addr) <{static_deltas = array<i64: 1>}> : (!tta.addr<f32, 1, 1>) -> !tta.addr<f32, 1, 1>
      scf.yield %next_src, %next_dst : !tta.addr<f32, 1, 1>, !tta.addr<f32, 1, 1>
    }
    tt.return
  }
}


// -----

module {
// CHECK-LABEL:   tt.func @loop_carried_addr_supported_index_iv(
// CHECK-SAME:      %[[ARG0:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG1:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG2:[-0-9A-Za-z$._]+]]: index) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 2 : i64
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 3 : i64
// CHECK:           %[[CONSTANT_2:.*]] = arith.constant 3 : index
// CHECK:           %[[CONSTANT_3:.*]] = arith.constant 2 : index
// CHECK:           %[[MAKE_ADDR_0:.*]] = tta.make_addr %[[ARG0]] to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
// CHECK:           %[[MAKE_ADDR_1:.*]] = tta.make_addr %[[ARG1]] to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
// CHECK:           %[[FOR_0:.*]]:2 = scf.for %[[VAL_0:.*]] = %[[CONSTANT_2]] to %[[ARG2]] step %[[CONSTANT_3]] iter_args(%[[VAL_1:.*]] = %[[MAKE_ADDR_0]], %[[VAL_2:.*]] = %[[MAKE_ADDR_1]]) -> (!tta.addr<f32, 1, 1>, !tta.addr<f32, 1, 1>) {
// CHECK:             %[[INDEX_CAST_0:.*]] = arith.index_cast %[[VAL_0]] : index to i64
// CHECK:             %[[SUBI_0:.*]] = arith.subi %[[INDEX_CAST_0]], %[[CONSTANT_1]] : i64
// CHECK:             %[[DIVSI_0:.*]] = arith.divsi %[[SUBI_0]], %[[CONSTANT_0]] : i64
// CHECK:             %[[INDEX_CAST_1:.*]] = arith.index_cast %[[DIVSI_0]] : i64 to index
// CHECK:             %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:             %[[ALLOC_0:.*]] = memref.alloc() : memref<4xf32>
// CHECK:             %[[REINTERPRET_CAST_0:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_0]] to offset: {{\[}}%[[INDEX_CAST_1]]], sizes: [4], strides: [1] : memref<*xf32> to memref<4xf32, strided<[1], offset: ?>>
// CHECK:             memref.copy %[[REINTERPRET_CAST_0]], %[[ALLOC_0]] : memref<4xf32, strided<[1], offset: ?>> to memref<4xf32>
// CHECK:             %[[TO_TENSOR_0:.*]] = bufferization.to_tensor %[[ALLOC_0]] restrict writable : memref<4xf32> to tensor<4xf32>
// CHECK:             %[[UNREALIZED_CONVERSION_CAST_1:.*]] = builtin.unrealized_conversion_cast %[[ARG1]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:             %[[REINTERPRET_CAST_1:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_1]] to offset: {{\[}}%[[INDEX_CAST_1]]], sizes: [4], strides: [1] : memref<*xf32> to memref<4xf32, strided<[1], offset: ?>>
// CHECK:             bufferization.materialize_in_destination %[[TO_TENSOR_0]] in writable %[[REINTERPRET_CAST_1]] : (tensor<4xf32>, memref<4xf32, strided<[1], offset: ?>>) -> ()
// CHECK:             %[[VAL_3:.*]] = "tta.advance"(%[[VAL_1]]) <{static_deltas = array<i64: 1>}> : (!tta.addr<f32, 1, 1>) -> !tta.addr<f32, 1, 1>
// CHECK:             %[[VAL_4:.*]] = "tta.advance"(%[[VAL_2]]) <{static_deltas = array<i64: 1>}> : (!tta.addr<f32, 1, 1>) -> !tta.addr<f32, 1, 1>
// CHECK:             scf.yield %[[VAL_3]], %[[VAL_4]] : !tta.addr<f32, 1, 1>, !tta.addr<f32, 1, 1>
// CHECK:           }
// CHECK:           tt.return
// CHECK:         }
  tt.func @loop_carried_addr_supported_index_iv(%src: !tt.ptr<f32>, %dst: !tt.ptr<f32>, %n: index) {
    %c3 = arith.constant 3 : index
    %c2 = arith.constant 2 : index
    %src_addr0 = tta.make_addr %src to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
    %dst_addr0 = tta.make_addr %dst to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
    %res:2 = scf.for %iv = %c3 to %n step %c2 iter_args(%src_addr = %src_addr0, %dst_addr = %dst_addr0) -> (!tta.addr<f32, 1, 1>, !tta.addr<f32, 1, 1>) {
      %val = "tta.load"(%src_addr) <{operandSegmentSizes = array<i32: 1, 0, 0>, static_mask_dims = array<i64>}> : (!tta.addr<f32, 1, 1>) -> tensor<4xf32>
      "tta.store"(%dst_addr, %val) <{static_mask_dims = array<i64>}> : (!tta.addr<f32, 1, 1>, tensor<4xf32>) -> ()
      %next_src = "tta.advance"(%src_addr) <{static_deltas = array<i64: 1>}> : (!tta.addr<f32, 1, 1>) -> !tta.addr<f32, 1, 1>
      %next_dst = "tta.advance"(%dst_addr) <{static_deltas = array<i64: 1>}> : (!tta.addr<f32, 1, 1>) -> !tta.addr<f32, 1, 1>
      scf.yield %next_src, %next_dst : !tta.addr<f32, 1, 1>, !tta.addr<f32, 1, 1>
    }
    tt.return
  }
}


// -----

module {
// CHECK-LABEL:   tt.func @loop_carried_addr_supported_reindex(
// CHECK-SAME:      %[[ARG0:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG1:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG2:[-0-9A-Za-z$._]+]]: i32) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 0 : i32
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 1 : i32
// CHECK:           %[[MAKE_ADDR_0:.*]] = tta.make_addr %[[ARG0]] to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
// CHECK:           %[[MAKE_ADDR_1:.*]] = tta.make_addr %[[ARG1]] to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
// CHECK:           %[[FOR_0:.*]]:2 = scf.for %[[VAL_0:.*]] = %[[CONSTANT_0]] to %[[ARG2]] step %[[CONSTANT_1]] iter_args(%[[VAL_1:.*]] = %[[MAKE_ADDR_0]], %[[VAL_2:.*]] = %[[MAKE_ADDR_1]]) -> (!tta.addr<f32, 1, 1>, !tta.addr<f32, 1, 1>)  : i32 {
// CHECK:             %[[INDEX_CAST_0:.*]] = arith.index_cast %[[VAL_0]] : i32 to index
// CHECK:             %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:             %[[ALLOC_0:.*]] = memref.alloc() : memref<4xf32>
// CHECK:             %[[REINTERPRET_CAST_0:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_0]] to offset: {{\[}}%[[INDEX_CAST_0]]], sizes: [4], strides: [1] : memref<*xf32> to memref<4xf32, strided<[1], offset: ?>>
// CHECK:             memref.copy %[[REINTERPRET_CAST_0]], %[[ALLOC_0]] : memref<4xf32, strided<[1], offset: ?>> to memref<4xf32>
// CHECK:             %[[TO_TENSOR_0:.*]] = bufferization.to_tensor %[[ALLOC_0]] restrict writable : memref<4xf32> to tensor<4xf32>
// CHECK:             %[[UNREALIZED_CONVERSION_CAST_1:.*]] = builtin.unrealized_conversion_cast %[[ARG1]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:             %[[REINTERPRET_CAST_1:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_1]] to offset: {{\[}}%[[INDEX_CAST_0]]], sizes: [4], strides: [1] : memref<*xf32> to memref<4xf32, strided<[1], offset: ?>>
// CHECK:             bufferization.materialize_in_destination %[[TO_TENSOR_0]] in writable %[[REINTERPRET_CAST_1]] : (tensor<4xf32>, memref<4xf32, strided<[1], offset: ?>>) -> ()
// CHECK:             %[[VAL_3:.*]] = "tta.reindex"(%[[VAL_1]]) <{static_offsets = array<i64: 1>}> : (!tta.addr<f32, 1, 1>) -> !tta.addr<f32, 1, 1>
// CHECK:             %[[VAL_4:.*]] = "tta.reindex"(%[[VAL_2]]) <{static_offsets = array<i64: 1>}> : (!tta.addr<f32, 1, 1>) -> !tta.addr<f32, 1, 1>
// CHECK:             scf.yield %[[VAL_3]], %[[VAL_4]] : !tta.addr<f32, 1, 1>, !tta.addr<f32, 1, 1>
// CHECK:           }
// CHECK:           tt.return
// CHECK:         }
  tt.func @loop_carried_addr_supported_reindex(%src: !tt.ptr<f32>, %dst: !tt.ptr<f32>, %n: i32) {
    %c0 = arith.constant 0 : i32
    %c1 = arith.constant 1 : i32
    %src_addr0 = tta.make_addr %src to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
    %dst_addr0 = tta.make_addr %dst to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
    %res:2 = scf.for %iv = %c0 to %n step %c1 iter_args(%src_addr = %src_addr0, %dst_addr = %dst_addr0) -> (!tta.addr<f32, 1, 1>, !tta.addr<f32, 1, 1>) : i32 {
      %val = "tta.load"(%src_addr) <{operandSegmentSizes = array<i32: 1, 0, 0>, static_mask_dims = array<i64>}> : (!tta.addr<f32, 1, 1>) -> tensor<4xf32>
      "tta.store"(%dst_addr, %val) <{static_mask_dims = array<i64>}> : (!tta.addr<f32, 1, 1>, tensor<4xf32>) -> ()
      %next_src = "tta.reindex"(%src_addr) <{static_offsets = array<i64: 1>}> : (!tta.addr<f32, 1, 1>) -> !tta.addr<f32, 1, 1>
      %next_dst = "tta.reindex"(%dst_addr) <{static_offsets = array<i64: 1>}> : (!tta.addr<f32, 1, 1>) -> !tta.addr<f32, 1, 1>
      scf.yield %next_src, %next_dst : !tta.addr<f32, 1, 1>, !tta.addr<f32, 1, 1>
    }
    tt.return
  }
}

// -----

module {
// CHECK-LABEL:   tt.func @loop_carried_addr_supported_derived_use(
// CHECK-SAME:      %[[ARG0:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG1:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG2:[-0-9A-Za-z$._]+]]: i32) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 3 : index
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 2 : index
// CHECK:           %[[CONSTANT_2:.*]] = arith.constant 0 : i32
// CHECK:           %[[CONSTANT_3:.*]] = arith.constant 1 : i32
// CHECK:           %[[MAKE_ADDR_0:.*]] = tta.make_addr %[[ARG0]] to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
// CHECK:           %[[MAKE_ADDR_1:.*]] = tta.make_addr %[[ARG1]] to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
// CHECK:           %[[FOR_0:.*]]:2 = scf.for %[[VAL_0:.*]] = %[[CONSTANT_2]] to %[[ARG2]] step %[[CONSTANT_3]] iter_args(%[[VAL_1:.*]] = %[[MAKE_ADDR_0]], %[[VAL_2:.*]] = %[[MAKE_ADDR_1]]) -> (!tta.addr<f32, 1, 1>, !tta.addr<f32, 1, 1>)  : i32 {
// CHECK:             %[[INDEX_CAST_0:.*]] = arith.index_cast %[[VAL_0]] : i32 to index
// CHECK:             %[[ADDI_0:.*]] = arith.addi %[[INDEX_CAST_0]], %[[CONSTANT_1]] : index
// CHECK:             %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:             %[[ALLOC_0:.*]] = memref.alloc() : memref<4xf32>
// CHECK:             %[[REINTERPRET_CAST_0:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_0]] to offset: {{\[}}%[[ADDI_0]]], sizes: [4], strides: [1] : memref<*xf32> to memref<4xf32, strided<[1], offset: ?>>
// CHECK:             memref.copy %[[REINTERPRET_CAST_0]], %[[ALLOC_0]] : memref<4xf32, strided<[1], offset: ?>> to memref<4xf32>
// CHECK:             %[[TO_TENSOR_0:.*]] = bufferization.to_tensor %[[ALLOC_0]] restrict writable : memref<4xf32> to tensor<4xf32>
// CHECK:             %[[ADDI_1:.*]] = arith.addi %[[INDEX_CAST_0]], %[[CONSTANT_0]] : index
// CHECK:             %[[UNREALIZED_CONVERSION_CAST_1:.*]] = builtin.unrealized_conversion_cast %[[ARG1]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:             %[[REINTERPRET_CAST_1:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_1]] to offset: {{\[}}%[[ADDI_1]]], sizes: [4], strides: [1] : memref<*xf32> to memref<4xf32, strided<[1], offset: ?>>
// CHECK:             bufferization.materialize_in_destination %[[TO_TENSOR_0]] in writable %[[REINTERPRET_CAST_1]] : (tensor<4xf32>, memref<4xf32, strided<[1], offset: ?>>) -> ()
// CHECK:             %[[VAL_3:.*]] = "tta.advance"(%[[VAL_1]]) <{static_deltas = array<i64: 1>}> : (!tta.addr<f32, 1, 1>) -> !tta.addr<f32, 1, 1>
// CHECK:             %[[VAL_4:.*]] = "tta.reindex"(%[[VAL_2]]) <{static_offsets = array<i64: 1>}> : (!tta.addr<f32, 1, 1>) -> !tta.addr<f32, 1, 1>
// CHECK:             scf.yield %[[VAL_3]], %[[VAL_4]] : !tta.addr<f32, 1, 1>, !tta.addr<f32, 1, 1>
// CHECK:           }
// CHECK:           tt.return
// CHECK:         }
  tt.func @loop_carried_addr_supported_derived_use(%src: !tt.ptr<f32>, %dst: !tt.ptr<f32>, %n: i32) {
    %c0 = arith.constant 0 : i32
    %c1 = arith.constant 1 : i32
    %src_addr0 = tta.make_addr %src to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
    %dst_addr0 = tta.make_addr %dst to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
    %res:2 = scf.for %iv = %c0 to %n step %c1 iter_args(%src_addr = %src_addr0, %dst_addr = %dst_addr0) -> (!tta.addr<f32, 1, 1>, !tta.addr<f32, 1, 1>) : i32 {
      %src_use = "tta.reindex"(%src_addr) <{static_offsets = array<i64: 2>}> : (!tta.addr<f32, 1, 1>) -> !tta.addr<f32, 1, 1>
      %dst_use = "tta.advance"(%dst_addr) <{static_deltas = array<i64: 3>}> : (!tta.addr<f32, 1, 1>) -> !tta.addr<f32, 1, 1>
      %val = "tta.load"(%src_use) <{operandSegmentSizes = array<i32: 1, 0, 0>, static_mask_dims = array<i64>}> : (!tta.addr<f32, 1, 1>) -> tensor<4xf32>
      "tta.store"(%dst_use, %val) <{static_mask_dims = array<i64>}> : (!tta.addr<f32, 1, 1>, tensor<4xf32>) -> ()
      %next_src = "tta.advance"(%src_addr) <{static_deltas = array<i64: 1>}> : (!tta.addr<f32, 1, 1>) -> !tta.addr<f32, 1, 1>
      %next_dst = "tta.reindex"(%dst_addr) <{static_offsets = array<i64: 1>}> : (!tta.addr<f32, 1, 1>) -> !tta.addr<f32, 1, 1>
      scf.yield %next_src, %next_dst : !tta.addr<f32, 1, 1>, !tta.addr<f32, 1, 1>
    }
    tt.return
  }
}

// -----

module {
// CHECK-LABEL:   tt.func @loop_carried_addr_supported_indirect_seed(
// CHECK-SAME:      %[[ARG0:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG1:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG2:[-0-9A-Za-z$._]+]]: i32) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant dense<[0, 1, 2, 3]> : tensor<4xindex>
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 1 : index
// CHECK:           %[[CONSTANT_2:.*]] = arith.constant 0 : index
// CHECK:           %[[CONSTANT_3:.*]] = arith.constant 4 : index
// CHECK:           %[[CONSTANT_4:.*]] = arith.constant 0 : i32
// CHECK:           %[[CONSTANT_5:.*]] = arith.constant 1 : i32
// CHECK:           %[[CONSTANT_6:.*]] = arith.constant dense<[0, 1, 2, 3]> : tensor<4xi32>
// CHECK:           %[[MAKE_ADDR_0:.*]] = tta.make_addr %[[ARG0]] to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
// CHECK:           %[[MAKE_ADDR_1:.*]] = tta.make_addr %[[ARG1]] to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
// CHECK:           %[[VAL_0:.*]] = "tta.indirect_reindex"(%[[MAKE_ADDR_0]], %[[CONSTANT_6]]) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 1, 1>, tensor<4xi32>) -> !tta.addr<f32, 1, 1>
// CHECK:           %[[VAL_1:.*]] = "tta.indirect_reindex"(%[[MAKE_ADDR_1]], %[[CONSTANT_6]]) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 1, 1>, tensor<4xi32>) -> !tta.addr<f32, 1, 1>
// CHECK:           %[[FOR_0:.*]]:2 = scf.for %[[VAL_2:.*]] = %[[CONSTANT_4]] to %[[ARG2]] step %[[CONSTANT_5]] iter_args(%[[VAL_3:.*]] = %[[VAL_0]], %[[VAL_4:.*]] = %[[VAL_1]]) -> (!tta.addr<f32, 1, 1>, !tta.addr<f32, 1, 1>)  : i32 {
// CHECK:             %[[INDEX_CAST_0:.*]] = arith.index_cast %[[VAL_2]] : i32 to index
// CHECK:             %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:             %[[ALLOC_0:.*]] = memref.alloc() : memref<4xf32>
// CHECK:             scf.for %[[VAL_5:.*]] = %[[CONSTANT_2]] to %[[CONSTANT_3]] step %[[CONSTANT_1]] {
// CHECK:               %[[EXTRACT_0:.*]] = tensor.extract %[[CONSTANT_0]]{{\[}}%[[VAL_5]]] : tensor<4xindex>
// CHECK:               %[[ADDI_0:.*]] = arith.addi %[[EXTRACT_0]], %[[INDEX_CAST_0]] : index
// CHECK:               %[[REINTERPRET_CAST_0:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_0]] to offset: {{\[}}%[[ADDI_0]]], sizes: [1], strides: [1] : memref<*xf32> to memref<1xf32, strided<[1], offset: ?>>
// CHECK:               %[[SUBVIEW_0:.*]] = memref.subview %[[ALLOC_0]]{{\[}}%[[VAL_5]]] [1] [1] : memref<4xf32> to memref<1xf32, strided<[1], offset: ?>>
// CHECK:               memref.copy %[[REINTERPRET_CAST_0]], %[[SUBVIEW_0]] : memref<1xf32, strided<[1], offset: ?>> to memref<1xf32, strided<[1], offset: ?>>
// CHECK:             }
// CHECK:             %[[TO_TENSOR_0:.*]] = bufferization.to_tensor %[[ALLOC_0]] restrict writable : memref<4xf32> to tensor<4xf32>
// CHECK:             %[[UNREALIZED_CONVERSION_CAST_1:.*]] = builtin.unrealized_conversion_cast %[[ARG1]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:             scf.for %[[VAL_6:.*]] = %[[CONSTANT_2]] to %[[CONSTANT_3]] step %[[CONSTANT_1]] {
// CHECK:               %[[EXTRACT_1:.*]] = tensor.extract %[[CONSTANT_0]]{{\[}}%[[VAL_6]]] : tensor<4xindex>
// CHECK:               %[[ADDI_1:.*]] = arith.addi %[[EXTRACT_1]], %[[INDEX_CAST_0]] : index
// CHECK:               %[[REINTERPRET_CAST_1:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_1]] to offset: {{\[}}%[[ADDI_1]]], sizes: [1], strides: [1] : memref<*xf32> to memref<1xf32, strided<[1], offset: ?>>
// CHECK:               %[[EXTRACT_SLICE_0:.*]] = tensor.extract_slice %[[TO_TENSOR_0]]{{\[}}%[[VAL_6]]] [1] [1] : tensor<4xf32> to tensor<1xf32>
// CHECK:               bufferization.materialize_in_destination %[[EXTRACT_SLICE_0]] in writable %[[REINTERPRET_CAST_1]] : (tensor<1xf32>, memref<1xf32, strided<[1], offset: ?>>) -> ()
// CHECK:             }
// CHECK:             %[[VAL_7:.*]] = "tta.advance"(%[[VAL_3]]) <{static_deltas = array<i64: 1>}> : (!tta.addr<f32, 1, 1>) -> !tta.addr<f32, 1, 1>
// CHECK:             %[[VAL_8:.*]] = "tta.reindex"(%[[VAL_4]]) <{static_offsets = array<i64: 1>}> : (!tta.addr<f32, 1, 1>) -> !tta.addr<f32, 1, 1>
// CHECK:             scf.yield %[[VAL_7]], %[[VAL_8]] : !tta.addr<f32, 1, 1>, !tta.addr<f32, 1, 1>
// CHECK:           }
// CHECK:           tt.return
// CHECK:         }
  tt.func @loop_carried_addr_supported_indirect_seed(%src: !tt.ptr<f32>, %dst: !tt.ptr<f32>, %n: i32) {
    %c0 = arith.constant 0 : i32
    %c1 = arith.constant 1 : i32
    %idx = arith.constant dense<[0, 1, 2, 3]> : tensor<4xi32>

    %src_base = tta.make_addr %src to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
    %dst_base = tta.make_addr %dst to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
    %src_addr0 = "tta.indirect_reindex"(%src_base, %idx) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 1, 1>, tensor<4xi32>) -> !tta.addr<f32, 1, 1>
    %dst_addr0 = "tta.indirect_reindex"(%dst_base, %idx) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 1, 1>, tensor<4xi32>) -> !tta.addr<f32, 1, 1>

    %res:2 = scf.for %iv = %c0 to %n step %c1 iter_args(%src_addr = %src_addr0, %dst_addr = %dst_addr0) -> (!tta.addr<f32, 1, 1>, !tta.addr<f32, 1, 1>) : i32 {
      %val = "tta.load"(%src_addr) <{operandSegmentSizes = array<i32: 1, 0, 0>, static_mask_dims = array<i64>}> : (!tta.addr<f32, 1, 1>) -> tensor<4xf32>
      "tta.store"(%dst_addr, %val) <{static_mask_dims = array<i64>}> : (!tta.addr<f32, 1, 1>, tensor<4xf32>) -> ()
      %next_src = "tta.advance"(%src_addr) <{static_deltas = array<i64: 1>}> : (!tta.addr<f32, 1, 1>) -> !tta.addr<f32, 1, 1>
      %next_dst = "tta.reindex"(%dst_addr) <{static_offsets = array<i64: 1>}> : (!tta.addr<f32, 1, 1>) -> !tta.addr<f32, 1, 1>
      scf.yield %next_src, %next_dst : !tta.addr<f32, 1, 1>, !tta.addr<f32, 1, 1>
    }
    tt.return
  }
}

// -----

module {
// CHECK-LABEL:   tt.func @loop_carried_addr_supported_indirect_recurrence(
// CHECK-SAME:      %[[ARG0:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG1:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG2:[-0-9A-Za-z$._]+]]: i32) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant dense<[0, 1, 2, 3]> : tensor<4xindex>
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 1 : index
// CHECK:           %[[CONSTANT_2:.*]] = arith.constant 4 : index
// CHECK:           %[[CONSTANT_3:.*]] = arith.constant 0 : index
// CHECK:           %[[CONSTANT_4:.*]] = arith.constant 0 : i32
// CHECK:           %[[CONSTANT_5:.*]] = arith.constant 1 : i32
// CHECK:           %[[CONSTANT_6:.*]] = arith.constant dense<[0, 1, 2, 3]> : tensor<4xi32>
// CHECK:           %[[MAKE_ADDR_0:.*]] = tta.make_addr %[[ARG0]] to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
// CHECK:           %[[VAL_0:.*]] = "tta.indirect_reindex"(%[[MAKE_ADDR_0]], %[[CONSTANT_6]]) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 1, 1>, tensor<4xi32>) -> !tta.addr<f32, 1, 1>
// CHECK:           %[[MAKE_ADDR_1:.*]] = tta.make_addr %[[ARG1]] to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
// CHECK:           %[[FOR_0:.*]]:2 = scf.for %[[VAL_1:.*]] = %[[CONSTANT_4]] to %[[ARG2]] step %[[CONSTANT_5]] iter_args(%[[VAL_2:.*]] = %[[VAL_0]], %[[VAL_3:.*]] = %[[MAKE_ADDR_1]]) -> (!tta.addr<f32, 1, 1>, !tta.addr<f32, 1, 1>)  : i32 {
// CHECK:             %[[INDEX_CAST_0:.*]] = arith.index_cast %[[VAL_1]] : i32 to index
// CHECK:             %[[SPLAT_0:.*]] = tensor.splat %[[INDEX_CAST_0]] : tensor<4xindex>
// CHECK:             %[[MULI_0:.*]] = arith.muli %[[SPLAT_0]], %[[CONSTANT_0]] : tensor<4xindex>
// CHECK:             %[[ADDI_0:.*]] = arith.addi %[[MULI_0]], %[[CONSTANT_0]] : tensor<4xindex>
// CHECK:             %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:             %[[ALLOC_0:.*]] = memref.alloc() : memref<4xf32>
// CHECK:             scf.for %[[VAL_4:.*]] = %[[CONSTANT_3]] to %[[CONSTANT_2]] step %[[CONSTANT_1]] {
// CHECK:               %[[EXTRACT_0:.*]] = tensor.extract %[[ADDI_0]]{{\[}}%[[VAL_4]]] : tensor<4xindex>
// CHECK:               %[[REINTERPRET_CAST_0:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_0]] to offset: {{\[}}%[[EXTRACT_0]]], sizes: [1], strides: [1] : memref<*xf32> to memref<1xf32, strided<[1], offset: ?>>
// CHECK:               %[[SUBVIEW_0:.*]] = memref.subview %[[ALLOC_0]]{{\[}}%[[VAL_4]]] [1] [1] : memref<4xf32> to memref<1xf32, strided<[1], offset: ?>>
// CHECK:               memref.copy %[[REINTERPRET_CAST_0]], %[[SUBVIEW_0]] : memref<1xf32, strided<[1], offset: ?>> to memref<1xf32, strided<[1], offset: ?>>
// CHECK:             }
// CHECK:             %[[TO_TENSOR_0:.*]] = bufferization.to_tensor %[[ALLOC_0]] restrict writable : memref<4xf32> to tensor<4xf32>
// CHECK:             %[[UNREALIZED_CONVERSION_CAST_1:.*]] = builtin.unrealized_conversion_cast %[[ARG1]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:             %[[REINTERPRET_CAST_1:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_1]] to offset: {{\[}}%[[INDEX_CAST_0]]], sizes: [4], strides: [1] : memref<*xf32> to memref<4xf32, strided<[1], offset: ?>>
// CHECK:             bufferization.materialize_in_destination %[[TO_TENSOR_0]] in writable %[[REINTERPRET_CAST_1]] : (tensor<4xf32>, memref<4xf32, strided<[1], offset: ?>>) -> ()
// CHECK:             %[[VAL_5:.*]] = "tta.indirect_reindex"(%[[VAL_2]], %[[CONSTANT_6]]) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 1, 1>, tensor<4xi32>) -> !tta.addr<f32, 1, 1>
// CHECK:             %[[VAL_6:.*]] = "tta.advance"(%[[VAL_3]]) <{static_deltas = array<i64: 1>}> : (!tta.addr<f32, 1, 1>) -> !tta.addr<f32, 1, 1>
// CHECK:             scf.yield %[[VAL_5]], %[[VAL_6]] : !tta.addr<f32, 1, 1>, !tta.addr<f32, 1, 1>
// CHECK:           }
// CHECK:           tt.return
// CHECK:         }
  tt.func @loop_carried_addr_supported_indirect_recurrence(%src: !tt.ptr<f32>, %dst: !tt.ptr<f32>, %n: i32) {
    %c0 = arith.constant 0 : i32
    %c1 = arith.constant 1 : i32
    %idx = arith.constant dense<[0, 1, 2, 3]> : tensor<4xi32>

    %src_base = tta.make_addr %src to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
    %src_addr0 = "tta.indirect_reindex"(%src_base, %idx) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 1, 1>, tensor<4xi32>) -> !tta.addr<f32, 1, 1>

    %dst_addr0 = tta.make_addr %dst to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>

    %res:2 = scf.for %iv = %c0 to %n step %c1 iter_args(%src_addr = %src_addr0, %dst_addr = %dst_addr0) -> (!tta.addr<f32, 1, 1>, !tta.addr<f32, 1, 1>) : i32 {
      %val = "tta.load"(%src_addr) <{operandSegmentSizes = array<i32: 1, 0, 0>, static_mask_dims = array<i64>}> : (!tta.addr<f32, 1, 1>) -> tensor<4xf32>
      "tta.store"(%dst_addr, %val) <{static_mask_dims = array<i64>}> : (!tta.addr<f32, 1, 1>, tensor<4xf32>) -> ()
      %next_src = "tta.indirect_reindex"(%src_addr, %idx) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 1, 1>, tensor<4xi32>) -> !tta.addr<f32, 1, 1>
      %next_dst = "tta.advance"(%dst_addr) <{static_deltas = array<i64: 1>}> : (!tta.addr<f32, 1, 1>) -> !tta.addr<f32, 1, 1>
      scf.yield %next_src, %next_dst : !tta.addr<f32, 1, 1>, !tta.addr<f32, 1, 1>
    }
    tt.return
  }
}

// -----

module {
// CHECK-LABEL:   tt.func @loop_carried_addr_supported_indirect_recurrence_no_seed(
// CHECK-SAME:      %[[ARG0:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG1:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG2:[-0-9A-Za-z$._]+]]: i32) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 1 : index
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 4 : index
// CHECK:           %[[CONSTANT_2:.*]] = arith.constant dense<[0, 1, 2, 3]> : tensor<4xindex>
// CHECK:           %[[CONSTANT_3:.*]] = arith.constant 0 : index
// CHECK:           %[[CONSTANT_4:.*]] = arith.constant 0 : i32
// CHECK:           %[[CONSTANT_5:.*]] = arith.constant 1 : i32
// CHECK:           %[[CONSTANT_6:.*]] = arith.constant dense<[0, 1, 2, 3]> : tensor<4xi32>
// CHECK:           %[[MAKE_ADDR_0:.*]] = tta.make_addr %[[ARG0]] to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
// CHECK:           %[[MAKE_ADDR_1:.*]] = tta.make_addr %[[ARG1]] to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
// CHECK:           %[[FOR_0:.*]]:2 = scf.for %[[VAL_0:.*]] = %[[CONSTANT_4]] to %[[ARG2]] step %[[CONSTANT_5]] iter_args(%[[VAL_1:.*]] = %[[MAKE_ADDR_0]], %[[VAL_2:.*]] = %[[MAKE_ADDR_1]]) -> (!tta.addr<f32, 1, 1>, !tta.addr<f32, 1, 1>)  : i32 {
// CHECK:             %[[INDEX_CAST_0:.*]] = arith.index_cast %[[VAL_0]] : i32 to index
// CHECK:             %[[CMPI_0:.*]] = arith.cmpi eq, %[[INDEX_CAST_0]], %[[CONSTANT_3]] : index
// CHECK:             %[[SPLAT_0:.*]] = tensor.splat %[[INDEX_CAST_0]] : tensor<4xindex>
// CHECK:             %[[MULI_0:.*]] = arith.muli %[[SPLAT_0]], %[[CONSTANT_2]] : tensor<4xindex>
// CHECK:             %[[SELECT_0:.*]] = arith.select %[[CMPI_0]], %[[CONSTANT_2]], %[[MULI_0]] : tensor<4xindex>
// CHECK:             %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:             %[[ALLOC_0:.*]] = memref.alloc() : memref<4xf32>
// CHECK:             scf.for %[[VAL_3:.*]] = %[[CONSTANT_3]] to %[[CONSTANT_1]] step %[[CONSTANT_0]] {
// CHECK:               %[[EXTRACT_0:.*]] = tensor.extract %[[SELECT_0]]{{\[}}%[[VAL_3]]] : tensor<4xindex>
// CHECK:               %[[REINTERPRET_CAST_0:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_0]] to offset: {{\[}}%[[EXTRACT_0]]], sizes: [1], strides: [1] : memref<*xf32> to memref<1xf32, strided<[1], offset: ?>>
// CHECK:               %[[SUBVIEW_0:.*]] = memref.subview %[[ALLOC_0]]{{\[}}%[[VAL_3]]] [1] [1] : memref<4xf32> to memref<1xf32, strided<[1], offset: ?>>
// CHECK:               memref.copy %[[REINTERPRET_CAST_0]], %[[SUBVIEW_0]] : memref<1xf32, strided<[1], offset: ?>> to memref<1xf32, strided<[1], offset: ?>>
// CHECK:             }
// CHECK:             %[[TO_TENSOR_0:.*]] = bufferization.to_tensor %[[ALLOC_0]] restrict writable : memref<4xf32> to tensor<4xf32>
// CHECK:             %[[UNREALIZED_CONVERSION_CAST_1:.*]] = builtin.unrealized_conversion_cast %[[ARG1]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:             %[[REINTERPRET_CAST_1:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_1]] to offset: {{\[}}%[[INDEX_CAST_0]]], sizes: [4], strides: [1] : memref<*xf32> to memref<4xf32, strided<[1], offset: ?>>
// CHECK:             bufferization.materialize_in_destination %[[TO_TENSOR_0]] in writable %[[REINTERPRET_CAST_1]] : (tensor<4xf32>, memref<4xf32, strided<[1], offset: ?>>) -> ()
// CHECK:             %[[VAL_4:.*]] = "tta.indirect_reindex"(%[[VAL_1]], %[[CONSTANT_6]]) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 1, 1>, tensor<4xi32>) -> !tta.addr<f32, 1, 1>
// CHECK:             %[[VAL_5:.*]] = "tta.advance"(%[[VAL_2]]) <{static_deltas = array<i64: 1>}> : (!tta.addr<f32, 1, 1>) -> !tta.addr<f32, 1, 1>
// CHECK:             scf.yield %[[VAL_4]], %[[VAL_5]] : !tta.addr<f32, 1, 1>, !tta.addr<f32, 1, 1>
// CHECK:           }
// CHECK:           tt.return
// CHECK:         }
  tt.func @loop_carried_addr_supported_indirect_recurrence_no_seed(%src: !tt.ptr<f32>, %dst: !tt.ptr<f32>, %n: i32) {
    %c0 = arith.constant 0 : i32
    %c1 = arith.constant 1 : i32
    %idx = arith.constant dense<[0, 1, 2, 3]> : tensor<4xi32>
    %addr0 = tta.make_addr %src to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
    %out0 = tta.make_addr %dst to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
    %res:2 = scf.for %iv = %c0 to %n step %c1 iter_args(%addr = %addr0, %out = %out0) -> (!tta.addr<f32, 1, 1>, !tta.addr<f32, 1, 1>) : i32 {
      %v = "tta.load"(%addr) <{operandSegmentSizes = array<i32: 1, 0, 0>, static_mask_dims = array<i64>}> : (!tta.addr<f32, 1, 1>) -> tensor<4xf32>
      "tta.store"(%out, %v) <{static_mask_dims = array<i64>}> : (!tta.addr<f32, 1, 1>, tensor<4xf32>) -> ()
      %next = "tta.indirect_reindex"(%addr, %idx) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 1, 1>, tensor<4xi32>) -> !tta.addr<f32, 1, 1>
      %next_out = "tta.advance"(%out) <{static_deltas = array<i64: 1>}> : (!tta.addr<f32, 1, 1>) -> !tta.addr<f32, 1, 1>
      scf.yield %next, %next_out : !tta.addr<f32, 1, 1>, !tta.addr<f32, 1, 1>
    }
    tt.return
  }
}

// -----

module {
// CHECK-LABEL:   tt.func @loop_carried_addr_supported_indirect_recurrence_no_seed_dynamic(
// CHECK-SAME:      %[[ARG0:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG1:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG2:[-0-9A-Za-z$._]+]]: tensor<?xi32>,
// CHECK-SAME:      %[[ARG3:[-0-9A-Za-z$._]+]]: tensor<?xi1>,
// CHECK-SAME:      %[[ARG4:[-0-9A-Za-z$._]+]]: i32) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 5 : index
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 2 : index
// CHECK:           %[[CONSTANT_2:.*]] = arith.constant 3 : index
// CHECK:           %[[CONSTANT_3:.*]] = arith.constant 1 : index
// CHECK:           %[[CONSTANT_4:.*]] = arith.constant 4 : index
// CHECK:           %[[CONSTANT_5:.*]] = arith.constant true
// CHECK:           %[[CONSTANT_6:.*]] = arith.constant 0 : index
// CHECK:           %[[CONSTANT_7:.*]] = arith.constant 0 : i32
// CHECK:           %[[CONSTANT_8:.*]] = arith.constant 1 : i32
// CHECK:           %[[MAKE_ADDR_0:.*]] = tta.make_addr %[[ARG0]] to sizes: [4], strides: [2], offsets: [3], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
// CHECK:           %[[MAKE_ADDR_1:.*]] = tta.make_addr %[[ARG1]] to sizes: [4], strides: [2], offsets: [5], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
// CHECK:           %[[FOR_0:.*]]:2 = scf.for %[[VAL_0:.*]] = %[[CONSTANT_7]] to %[[ARG4]] step %[[CONSTANT_8]] iter_args(%[[VAL_1:.*]] = %[[MAKE_ADDR_0]], %[[VAL_2:.*]] = %[[MAKE_ADDR_1]]) -> (!tta.addr<f32, 1, 1>, !tta.addr<f32, 1, 1>)  : i32 {
// CHECK:             %[[INDEX_CAST_0:.*]] = arith.index_cast %[[VAL_0]] : i32 to index
// CHECK:             %[[INDEX_CAST_1:.*]] = arith.index_cast %[[ARG2]] : tensor<?xi32> to tensor<?xindex>
// CHECK:             %[[CMPI_0:.*]] = arith.cmpi eq, %[[INDEX_CAST_0]], %[[CONSTANT_6]] : index
// CHECK:             %[[DIM_0:.*]] = tensor.dim %[[INDEX_CAST_1]], %[[CONSTANT_6]] : tensor<?xindex>
// CHECK:             %[[SPLAT_0:.*]] = tensor.splat %[[INDEX_CAST_0]]{{\[}}%[[DIM_0]]] : tensor<?xindex>
// CHECK:             %[[MULI_0:.*]] = arith.muli %[[INDEX_CAST_1]], %[[SPLAT_0]] : tensor<?xindex>
// CHECK:             %[[GENERATE_0:.*]] = tensor.generate %[[DIM_0]] {
// CHECK:             ^bb0(%[[VAL_3:.*]]: index):
// CHECK:               tensor.yield %[[VAL_3]] : index
// CHECK:             } : tensor<?xindex>
// CHECK:             %[[SELECT_0:.*]] = arith.select %[[CMPI_0]], %[[VAL_4:.*]], %[[MULI_0]] : tensor<?xindex>
// CHECK:             %[[DIM_1:.*]] = tensor.dim %[[ARG3]], %[[CONSTANT_6]] : tensor<?xi1>
// CHECK:             %[[GENERATE_1:.*]] = tensor.generate %[[DIM_1]] {
// CHECK:             ^bb0(%[[VAL_5:.*]]: index):
// CHECK:               tensor.yield %[[CONSTANT_5]] : i1
// CHECK:             } : tensor<?xi1>
// CHECK:             %[[SELECT_1:.*]] = arith.select %[[CMPI_0]], %[[VAL_6:.*]], %[[ARG3]] : tensor<?xi1>
// CHECK:             %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:             %[[ALLOC_0:.*]] = memref.alloc() : memref<4xf32>
// CHECK:             %[[DIM_2:.*]] = tensor.dim %[[SELECT_0]], %[[CONSTANT_6]] : tensor<?xindex>
// CHECK:             %[[MINSI_0:.*]] = arith.minsi %[[DIM_2]], %[[CONSTANT_4]] : index
// CHECK:             scf.for %[[VAL_7:.*]] = %[[CONSTANT_6]] to %[[MINSI_0]] step %[[CONSTANT_3]] {
// CHECK:               %[[EXTRACT_0:.*]] = tensor.extract %[[SELECT_1]]{{\[}}%[[VAL_7]]] : tensor<?xi1>
// CHECK:               scf.if %[[EXTRACT_0]] {
// CHECK:                 %[[EXTRACT_1:.*]] = tensor.extract %[[SELECT_0]]{{\[}}%[[VAL_7]]] : tensor<?xindex>
// CHECK:                 %[[ADDI_0:.*]] = arith.addi %[[EXTRACT_1]], %[[CONSTANT_2]] : index
// CHECK:                 %[[MULI_1:.*]] = arith.muli %[[ADDI_0]], %[[CONSTANT_1]] : index
// CHECK:                 %[[REINTERPRET_CAST_0:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_0]] to offset: {{\[}}%[[MULI_1]]], sizes: [1], strides: [2] : memref<*xf32> to memref<1xf32, strided<[2], offset: ?>>
// CHECK:                 %[[SUBVIEW_0:.*]] = memref.subview %[[ALLOC_0]]{{\[}}%[[VAL_7]]] [1] [1] : memref<4xf32> to memref<1xf32, strided<[1], offset: ?>>
// CHECK:                 memref.copy %[[REINTERPRET_CAST_0]], %[[SUBVIEW_0]] : memref<1xf32, strided<[2], offset: ?>> to memref<1xf32, strided<[1], offset: ?>>
// CHECK:               }
// CHECK:             }
// CHECK:             %[[TO_TENSOR_0:.*]] = bufferization.to_tensor %[[ALLOC_0]] restrict writable : memref<4xf32> to tensor<4xf32>
// CHECK:             %[[ADDI_1:.*]] = arith.addi %[[INDEX_CAST_0]], %[[CONSTANT_0]] : index
// CHECK:             %[[UNREALIZED_CONVERSION_CAST_1:.*]] = builtin.unrealized_conversion_cast %[[ARG1]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:             %[[REINTERPRET_CAST_1:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_1]] to offset: {{\[}}%[[ADDI_1]]], sizes: [4], strides: [2] : memref<*xf32> to memref<4xf32, strided<[2], offset: ?>>
// CHECK:             bufferization.materialize_in_destination %[[TO_TENSOR_0]] in writable %[[REINTERPRET_CAST_1]] : (tensor<4xf32>, memref<4xf32, strided<[2], offset: ?>>) -> ()
// CHECK:             %[[VAL_8:.*]] = "tta.indirect_reindex"(%[[VAL_1]], %[[ARG2]], %[[ARG3]]) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 1, 1>, tensor<?xi32>, tensor<?xi1>) -> !tta.addr<f32, 1, 1>
// CHECK:             %[[VAL_9:.*]] = "tta.advance"(%[[VAL_2]]) <{static_deltas = array<i64: 1>}> : (!tta.addr<f32, 1, 1>) -> !tta.addr<f32, 1, 1>
// CHECK:             scf.yield %[[VAL_8]], %[[VAL_9]] : !tta.addr<f32, 1, 1>, !tta.addr<f32, 1, 1>
// CHECK:           }
// CHECK:           tt.return
// CHECK:         }
  tt.func @loop_carried_addr_supported_indirect_recurrence_no_seed_dynamic(%src: !tt.ptr<f32>, %dst: !tt.ptr<f32>, %idx: tensor<?xi32>, %mask: tensor<?xi1>, %n: i32) {
    %c0 = arith.constant 0 : i32
    %c1 = arith.constant 1 : i32
    %addr0 = tta.make_addr %src to sizes: [4], strides: [2], offsets: [3], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
    %out0 = tta.make_addr %dst to sizes: [4], strides: [2], offsets: [5], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
    %res:2 = scf.for %iv = %c0 to %n step %c1 iter_args(%addr = %addr0, %out = %out0) -> (!tta.addr<f32, 1, 1>, !tta.addr<f32, 1, 1>) : i32 {
      %v = "tta.load"(%addr) <{operandSegmentSizes = array<i32: 1, 0, 0>, static_mask_dims = array<i64>}> : (!tta.addr<f32, 1, 1>) -> tensor<4xf32>
      "tta.store"(%out, %v) <{static_mask_dims = array<i64>}> : (!tta.addr<f32, 1, 1>, tensor<4xf32>) -> ()
      %next = "tta.indirect_reindex"(%addr, %idx, %mask) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 1, 1>, tensor<?xi32>, tensor<?xi1>) -> !tta.addr<f32, 1, 1>
      %next_out = "tta.advance"(%out) <{static_deltas = array<i64: 1>}> : (!tta.addr<f32, 1, 1>) -> !tta.addr<f32, 1, 1>
      scf.yield %next, %next_out : !tta.addr<f32, 1, 1>, !tta.addr<f32, 1, 1>
    }
    tt.return
  }
}

// -----

module {
// CHECK-LABEL:   tt.func @loop_carried_addr_supported_indirect_recurrence_multi_dim_mixed_seed(
// CHECK-SAME:      %[[ARG0:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG1:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG2:[-0-9A-Za-z$._]+]]: i32) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant dense<[0, 1]> : tensor<2xindex>
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 1 : index
// CHECK:           %[[CONSTANT_2:.*]] = arith.constant 4 : index
// CHECK:           %[[CONSTANT_3:.*]] = arith.constant 2 : index
// CHECK:           %[[CONSTANT_4:.*]] = arith.constant dense<[0, 1, 2, 3]> : tensor<4xindex>
// CHECK:           %[[CONSTANT_5:.*]] = arith.constant 0 : index
// CHECK:           %[[CONSTANT_6:.*]] = arith.constant 0 : i32
// CHECK:           %[[CONSTANT_7:.*]] = arith.constant 1 : i32
// CHECK:           %[[CONSTANT_8:.*]] = arith.constant dense<[0, 1]> : tensor<2xi32>
// CHECK:           %[[CONSTANT_9:.*]] = arith.constant dense<[0, 1, 2, 3]> : tensor<4xi32>
// CHECK:           %[[MAKE_ADDR_0:.*]] = tta.make_addr %[[ARG0]] to sizes: [2, 4], strides: [4, 1], offsets: [0, 0], wrap_boundaries: [0, 0], layout: "strided" : <f32> to !tta.addr<f32, 2, 1>
// CHECK:           %[[VAL_0:.*]] = "tta.indirect_reindex"(%[[MAKE_ADDR_0]], %[[CONSTANT_8]]) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 2, 1>, tensor<2xi32>) -> !tta.addr<f32, 2, 1>
// CHECK:           %[[MAKE_ADDR_1:.*]] = tta.make_addr %[[ARG1]] to sizes: [2, 4], strides: [4, 1], offsets: [0, 0], wrap_boundaries: [0, 0], layout: "strided" : <f32> to !tta.addr<f32, 2, 1>
// CHECK:           %[[FOR_0:.*]]:2 = scf.for %[[VAL_1:.*]] = %[[CONSTANT_6]] to %[[ARG2]] step %[[CONSTANT_7]] iter_args(%[[VAL_2:.*]] = %[[VAL_0]], %[[VAL_3:.*]] = %[[MAKE_ADDR_1]]) -> (!tta.addr<f32, 2, 1>, !tta.addr<f32, 2, 1>)  : i32 {
// CHECK:             %[[INDEX_CAST_0:.*]] = arith.index_cast %[[VAL_1]] : i32 to index
// CHECK:             %[[CMPI_0:.*]] = arith.cmpi eq, %[[INDEX_CAST_0]], %[[CONSTANT_5]] : index
// CHECK:             %[[SPLAT_0:.*]] = tensor.splat %[[INDEX_CAST_0]] : tensor<2xindex>
// CHECK:             %[[MULI_0:.*]] = arith.muli %[[SPLAT_0]], %[[CONSTANT_0]] : tensor<2xindex>
// CHECK:             %[[ADDI_0:.*]] = arith.addi %[[MULI_0]], %[[CONSTANT_0]] : tensor<2xindex>
// CHECK:             %[[SPLAT_1:.*]] = tensor.splat %[[INDEX_CAST_0]] : tensor<4xindex>
// CHECK:             %[[MULI_1:.*]] = arith.muli %[[SPLAT_1]], %[[CONSTANT_4]] : tensor<4xindex>
// CHECK:             %[[SELECT_0:.*]] = arith.select %[[CMPI_0]], %[[CONSTANT_4]], %[[MULI_1]] : tensor<4xindex>
// CHECK:             %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:             %[[ALLOC_0:.*]] = memref.alloc() : memref<2x4xf32>
// CHECK:             %[[CAST_0:.*]] = memref.cast %[[UNREALIZED_CONVERSION_CAST_0]] : memref<*xf32> to memref<?xf32>
// CHECK:             scf.for %[[VAL_4:.*]] = %[[CONSTANT_5]] to %[[CONSTANT_3]] step %[[CONSTANT_1]] {
// CHECK:               scf.for %[[VAL_5:.*]] = %[[CONSTANT_5]] to %[[CONSTANT_2]] step %[[CONSTANT_1]] {
// CHECK:                 %[[EXTRACT_0:.*]] = tensor.extract %[[ADDI_0]]{{\[}}%[[VAL_4]]] : tensor<2xindex>
// CHECK:                 %[[MULI_2:.*]] = arith.muli %[[EXTRACT_0]], %[[CONSTANT_2]] : index
// CHECK:                 %[[EXTRACT_1:.*]] = tensor.extract %[[SELECT_0]]{{\[}}%[[VAL_5]]] : tensor<4xindex>
// CHECK:                 %[[ADDI_1:.*]] = arith.addi %[[MULI_2]], %[[EXTRACT_1]] : index
// CHECK:                 %[[LOAD_0:.*]] = memref.load %[[CAST_0]]{{\[}}%[[ADDI_1]]] : memref<?xf32>
// CHECK:                 memref.store %[[LOAD_0]], %[[ALLOC_0]]{{\[}}%[[VAL_4]], %[[VAL_5]]] : memref<2x4xf32>
// CHECK:               }
// CHECK:             }
// CHECK:             %[[TO_TENSOR_0:.*]] = bufferization.to_tensor %[[ALLOC_0]] restrict writable : memref<2x4xf32> to tensor<2x4xf32>
// CHECK:             %[[UNREALIZED_CONVERSION_CAST_1:.*]] = builtin.unrealized_conversion_cast %[[ARG1]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:             %[[REINTERPRET_CAST_0:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_1]] to offset: {{\[}}%[[INDEX_CAST_0]]], sizes: [2, 4], strides: [4, 1] : memref<*xf32> to memref<2x4xf32, strided<[4, 1], offset: ?>>
// CHECK:             bufferization.materialize_in_destination %[[TO_TENSOR_0]] in writable %[[REINTERPRET_CAST_0]] : (tensor<2x4xf32>, memref<2x4xf32, strided<[4, 1], offset: ?>>) -> ()
// CHECK:             %[[VAL_6:.*]] = "tta.indirect_reindex"(%[[VAL_2]], %[[CONSTANT_8]]) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 2, 1>, tensor<2xi32>) -> !tta.addr<f32, 2, 1>
// CHECK:             %[[VAL_7:.*]] = "tta.indirect_reindex"(%[[VAL_6]], %[[CONSTANT_9]]) <{indirect_dim = 1 : i32}> : (!tta.addr<f32, 2, 1>, tensor<4xi32>) -> !tta.addr<f32, 2, 1>
// CHECK:             %[[VAL_8:.*]] = "tta.advance"(%[[VAL_3]]) <{static_deltas = array<i64: 1, 0>}> : (!tta.addr<f32, 2, 1>) -> !tta.addr<f32, 2, 1>
// CHECK:             scf.yield %[[VAL_7]], %[[VAL_8]] : !tta.addr<f32, 2, 1>, !tta.addr<f32, 2, 1>
// CHECK:           }
// CHECK:           tt.return
// CHECK:         }
  tt.func @loop_carried_addr_supported_indirect_recurrence_multi_dim_mixed_seed(%src: !tt.ptr<f32>, %dst: !tt.ptr<f32>, %n: i32) {
    %c0 = arith.constant 0 : i32
    %c1 = arith.constant 1 : i32
    %idx0 = arith.constant dense<[0, 1]> : tensor<2xi32>
    %idx1 = arith.constant dense<[0, 1, 2, 3]> : tensor<4xi32>

    %src_base = tta.make_addr %src to sizes: [2, 4], strides: [4, 1], offsets: [0, 0], wrap_boundaries: [0, 0], layout: "strided" : <f32> to !tta.addr<f32, 2, 1>
    %src_seed = "tta.indirect_reindex"(%src_base, %idx0) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 2, 1>, tensor<2xi32>) -> !tta.addr<f32, 2, 1>
    %dst_addr0 = tta.make_addr %dst to sizes: [2, 4], strides: [4, 1], offsets: [0, 0], wrap_boundaries: [0, 0], layout: "strided" : <f32> to !tta.addr<f32, 2, 1>

    %res:2 = scf.for %iv = %c0 to %n step %c1 iter_args(%src_addr = %src_seed, %dst_addr = %dst_addr0) -> (!tta.addr<f32, 2, 1>, !tta.addr<f32, 2, 1>) : i32 {
      %val = "tta.load"(%src_addr) <{operandSegmentSizes = array<i32: 1, 0, 0>, static_mask_dims = array<i64>}> : (!tta.addr<f32, 2, 1>) -> tensor<2x4xf32>
      "tta.store"(%dst_addr, %val) <{static_mask_dims = array<i64>}> : (!tta.addr<f32, 2, 1>, tensor<2x4xf32>) -> ()
      %next_src0 = "tta.indirect_reindex"(%src_addr, %idx0) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 2, 1>, tensor<2xi32>) -> !tta.addr<f32, 2, 1>
      %next_src1 = "tta.indirect_reindex"(%next_src0, %idx1) <{indirect_dim = 1 : i32}> : (!tta.addr<f32, 2, 1>, tensor<4xi32>) -> !tta.addr<f32, 2, 1>
      %next_dst = "tta.advance"(%dst_addr) <{static_deltas = array<i64: 1, 0>}> : (!tta.addr<f32, 2, 1>) -> !tta.addr<f32, 2, 1>
      scf.yield %next_src1, %next_dst : !tta.addr<f32, 2, 1>, !tta.addr<f32, 2, 1>
    }
    tt.return
  }
}

// -----

module {
// CHECK-LABEL:   tt.func @loop_carried_addr_supported_indirect_recurrence_multi_dim_dynamic_wrap(
// CHECK-SAME:      %[[ARG0:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG1:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG2:[-0-9A-Za-z$._]+]]: tensor<?xi32>,
// CHECK-SAME:      %[[ARG3:[-0-9A-Za-z$._]+]]: tensor<?xi1>,
// CHECK-SAME:      %[[ARG4:[-0-9A-Za-z$._]+]]: i32) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant dense<[0, 1]> : tensor<2xindex>
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 11 : index
// CHECK:           %[[CONSTANT_2:.*]] = arith.constant 7 : index
// CHECK:           %[[CONSTANT_3:.*]] = arith.constant 9 : index
// CHECK:           %[[CONSTANT_4:.*]] = arith.constant 3 : index
// CHECK:           %[[CONSTANT_5:.*]] = arith.constant 5 : index
// CHECK:           %[[CONSTANT_6:.*]] = arith.constant 1 : index
// CHECK:           %[[CONSTANT_7:.*]] = arith.constant 4 : index
// CHECK:           %[[CONSTANT_8:.*]] = arith.constant 2 : index
// CHECK:           %[[CONSTANT_9:.*]] = arith.constant true
// CHECK:           %[[CONSTANT_10:.*]] = arith.constant 0 : index
// CHECK:           %[[CONSTANT_11:.*]] = arith.constant 0 : i32
// CHECK:           %[[CONSTANT_12:.*]] = arith.constant 1 : i32
// CHECK:           %[[CONSTANT_13:.*]] = arith.constant dense<[0, 1]> : tensor<2xi32>
// CHECK:           %[[CONSTANT_14:.*]] = arith.constant dense<[true, false]> : tensor<2xi1>
// CHECK:           %[[MAKE_ADDR_0:.*]] = tta.make_addr %[[ARG0]] to sizes: [2, 4], strides: [4, 1], offsets: [1, 3], wrap_boundaries: [5, 9], layout: "strided" : <f32> to !tta.addr<f32, 2, 1>
// CHECK:           %[[VAL_0:.*]] = "tta.indirect_reindex"(%[[MAKE_ADDR_0]], %[[CONSTANT_13]], %[[CONSTANT_14]]) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 2, 1>, tensor<2xi32>, tensor<2xi1>) -> !tta.addr<f32, 2, 1>
// CHECK:           %[[MAKE_ADDR_1:.*]] = tta.make_addr %[[ARG1]] to sizes: [2, 4], strides: [4, 1], offsets: [0, 2], wrap_boundaries: [7, 11], layout: "strided" : <f32> to !tta.addr<f32, 2, 1>
// CHECK:           %[[FOR_0:.*]]:2 = scf.for %[[VAL_1:.*]] = %[[CONSTANT_11]] to %[[ARG4]] step %[[CONSTANT_12]] iter_args(%[[VAL_2:.*]] = %[[VAL_0]], %[[VAL_3:.*]] = %[[MAKE_ADDR_1]]) -> (!tta.addr<f32, 2, 1>, !tta.addr<f32, 2, 1>)  : i32 {
// CHECK:             %[[INDEX_CAST_0:.*]] = arith.index_cast %[[VAL_1]] : i32 to index
// CHECK:             %[[INDEX_CAST_1:.*]] = arith.index_cast %[[ARG2]] : tensor<?xi32> to tensor<?xindex>
// CHECK:             %[[CMPI_0:.*]] = arith.cmpi eq, %[[INDEX_CAST_0]], %[[CONSTANT_10]] : index
// CHECK:             %[[SPLAT_0:.*]] = tensor.splat %[[INDEX_CAST_0]] : tensor<2xindex>
// CHECK:             %[[MULI_0:.*]] = arith.muli %[[SPLAT_0]], %[[CONSTANT_0]] : tensor<2xindex>
// CHECK:             %[[ADDI_0:.*]] = arith.addi %[[MULI_0]], %[[CONSTANT_0]] : tensor<2xindex>
// CHECK:             %[[DIM_0:.*]] = tensor.dim %[[INDEX_CAST_1]], %[[CONSTANT_10]] : tensor<?xindex>
// CHECK:             %[[SPLAT_1:.*]] = tensor.splat %[[INDEX_CAST_0]]{{\[}}%[[DIM_0]]] : tensor<?xindex>
// CHECK:             %[[MULI_1:.*]] = arith.muli %[[INDEX_CAST_1]], %[[SPLAT_1]] : tensor<?xindex>
// CHECK:             %[[GENERATE_0:.*]] = tensor.generate %[[DIM_0]] {
// CHECK:             ^bb0(%[[VAL_4:.*]]: index):
// CHECK:               tensor.yield %[[VAL_4]] : index
// CHECK:             } : tensor<?xindex>
// CHECK:             %[[SELECT_0:.*]] = arith.select %[[CMPI_0]], %[[VAL_5:.*]], %[[MULI_1]] : tensor<?xindex>
// CHECK:             %[[DIM_1:.*]] = tensor.dim %[[ARG3]], %[[CONSTANT_10]] : tensor<?xi1>
// CHECK:             %[[GENERATE_1:.*]] = tensor.generate %[[DIM_1]] {
// CHECK:             ^bb0(%[[VAL_6:.*]]: index):
// CHECK:               tensor.yield %[[CONSTANT_9]] : i1
// CHECK:             } : tensor<?xi1>
// CHECK:             %[[SELECT_1:.*]] = arith.select %[[CMPI_0]], %[[VAL_7:.*]], %[[ARG3]] : tensor<?xi1>
// CHECK:             %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:             %[[ALLOC_0:.*]] = memref.alloc() : memref<2x4xf32>
// CHECK:             %[[CAST_0:.*]] = memref.cast %[[UNREALIZED_CONVERSION_CAST_0]] : memref<*xf32> to memref<?xf32>
// CHECK:             %[[DIM_2:.*]] = tensor.dim %[[SELECT_0]], %[[CONSTANT_10]] : tensor<?xindex>
// CHECK:             %[[MINSI_0:.*]] = arith.minsi %[[DIM_2]], %[[CONSTANT_7]] : index
// CHECK:             scf.for %[[VAL_8:.*]] = %[[CONSTANT_10]] to %[[CONSTANT_8]] step %[[CONSTANT_6]] {
// CHECK:               scf.for %[[VAL_9:.*]] = %[[CONSTANT_10]] to %[[MINSI_0]] step %[[CONSTANT_6]] {
// CHECK:                 %[[EXTRACT_0:.*]] = tensor.extract %[[CONSTANT_14]]{{\[}}%[[VAL_8]]] : tensor<2xi1>
// CHECK:                 %[[EXTRACT_1:.*]] = tensor.extract %[[SELECT_1]]{{\[}}%[[VAL_9]]] : tensor<?xi1>
// CHECK:                 %[[ANDI_0:.*]] = arith.andi %[[EXTRACT_0]], %[[EXTRACT_1]] : i1
// CHECK:                 scf.if %[[ANDI_0]] {
// CHECK:                   %[[EXTRACT_2:.*]] = tensor.extract %[[ADDI_0]]{{\[}}%[[VAL_8]]] : tensor<2xindex>
// CHECK:                   %[[MULI_2:.*]] = arith.muli %[[EXTRACT_2]], %[[CONSTANT_7]] : index
// CHECK:                   %[[ADDI_1:.*]] = arith.addi %[[MULI_2]], %[[CONSTANT_6]] : index
// CHECK:                   %[[REMSI_0:.*]] = arith.remsi %[[ADDI_1]], %[[CONSTANT_5]] : index
// CHECK:                   %[[CMPI_1:.*]] = arith.cmpi slt, %[[REMSI_0]], %[[CONSTANT_10]] : index
// CHECK:                   %[[ADDI_2:.*]] = arith.addi %[[REMSI_0]], %[[CONSTANT_5]] : index
// CHECK:                   %[[SELECT_2:.*]] = arith.select %[[CMPI_1]], %[[ADDI_2]], %[[REMSI_0]] : index
// CHECK:                   %[[EXTRACT_3:.*]] = tensor.extract %[[SELECT_0]]{{\[}}%[[VAL_9]]] : tensor<?xindex>
// CHECK:                   %[[ADDI_3:.*]] = arith.addi %[[EXTRACT_3]], %[[CONSTANT_4]] : index
// CHECK:                   %[[REMSI_1:.*]] = arith.remsi %[[ADDI_3]], %[[CONSTANT_3]] : index
// CHECK:                   %[[CMPI_2:.*]] = arith.cmpi slt, %[[REMSI_1]], %[[CONSTANT_10]] : index
// CHECK:                   %[[ADDI_4:.*]] = arith.addi %[[REMSI_1]], %[[CONSTANT_3]] : index
// CHECK:                   %[[SELECT_3:.*]] = arith.select %[[CMPI_2]], %[[ADDI_4]], %[[REMSI_1]] : index
// CHECK:                   %[[ADDI_5:.*]] = arith.addi %[[SELECT_2]], %[[SELECT_3]] : index
// CHECK:                   %[[LOAD_0:.*]] = memref.load %[[CAST_0]]{{\[}}%[[ADDI_5]]] : memref<?xf32>
// CHECK:                   memref.store %[[LOAD_0]], %[[ALLOC_0]]{{\[}}%[[VAL_8]], %[[VAL_9]]] : memref<2x4xf32>
// CHECK:                 }
// CHECK:               }
// CHECK:             }
// CHECK:             %[[TO_TENSOR_0:.*]] = bufferization.to_tensor %[[ALLOC_0]] restrict writable : memref<2x4xf32> to tensor<2x4xf32>
// CHECK:             %[[ADDI_6:.*]] = arith.addi %[[INDEX_CAST_0]], %[[CONSTANT_8]] : index
// CHECK:             %[[UNREALIZED_CONVERSION_CAST_1:.*]] = builtin.unrealized_conversion_cast %[[ARG1]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:             %[[CAST_1:.*]] = memref.cast %[[UNREALIZED_CONVERSION_CAST_1]] : memref<*xf32> to memref<?xf32>
// CHECK:             scf.for %[[VAL_10:.*]] = %[[CONSTANT_10]] to %[[CONSTANT_8]] step %[[CONSTANT_6]] {
// CHECK:               scf.for %[[VAL_11:.*]] = %[[CONSTANT_10]] to %[[CONSTANT_7]] step %[[CONSTANT_6]] {
// CHECK:                 %[[MULI_3:.*]] = arith.muli %[[VAL_10]], %[[CONSTANT_7]] : index
// CHECK:                 %[[REMSI_2:.*]] = arith.remsi %[[MULI_3]], %[[CONSTANT_2]] : index
// CHECK:                 %[[CMPI_3:.*]] = arith.cmpi slt, %[[REMSI_2]], %[[CONSTANT_10]] : index
// CHECK:                 %[[ADDI_7:.*]] = arith.addi %[[REMSI_2]], %[[CONSTANT_2]] : index
// CHECK:                 %[[SELECT_4:.*]] = arith.select %[[CMPI_3]], %[[ADDI_7]], %[[REMSI_2]] : index
// CHECK:                 %[[ADDI_8:.*]] = arith.addi %[[ADDI_6]], %[[VAL_11]] : index
// CHECK:                 %[[REMSI_3:.*]] = arith.remsi %[[ADDI_8]], %[[CONSTANT_1]] : index
// CHECK:                 %[[CMPI_4:.*]] = arith.cmpi slt, %[[REMSI_3]], %[[CONSTANT_10]] : index
// CHECK:                 %[[ADDI_9:.*]] = arith.addi %[[REMSI_3]], %[[CONSTANT_1]] : index
// CHECK:                 %[[SELECT_5:.*]] = arith.select %[[CMPI_4]], %[[ADDI_9]], %[[REMSI_3]] : index
// CHECK:                 %[[ADDI_10:.*]] = arith.addi %[[SELECT_4]], %[[SELECT_5]] : index
// CHECK:                 %[[EXTRACT_4:.*]] = tensor.extract %[[TO_TENSOR_0]]{{\[}}%[[VAL_10]], %[[VAL_11]]] : tensor<2x4xf32>
// CHECK:                 memref.store %[[EXTRACT_4]], %[[CAST_1]]{{\[}}%[[ADDI_10]]] : memref<?xf32>
// CHECK:               }
// CHECK:             }
// CHECK:             %[[VAL_12:.*]] = "tta.indirect_reindex"(%[[VAL_2]], %[[CONSTANT_13]], %[[CONSTANT_14]]) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 2, 1>, tensor<2xi32>, tensor<2xi1>) -> !tta.addr<f32, 2, 1>
// CHECK:             %[[VAL_13:.*]] = "tta.indirect_reindex"(%[[VAL_12]], %[[ARG2]], %[[ARG3]]) <{indirect_dim = 1 : i32}> : (!tta.addr<f32, 2, 1>, tensor<?xi32>, tensor<?xi1>) -> !tta.addr<f32, 2, 1>
// CHECK:             %[[VAL_14:.*]] = "tta.advance"(%[[VAL_3]]) <{static_deltas = array<i64: 0, 1>}> : (!tta.addr<f32, 2, 1>) -> !tta.addr<f32, 2, 1>
// CHECK:             scf.yield %[[VAL_13]], %[[VAL_14]] : !tta.addr<f32, 2, 1>, !tta.addr<f32, 2, 1>
// CHECK:           }
// CHECK:           tt.return
// CHECK:         }
  tt.func @loop_carried_addr_supported_indirect_recurrence_multi_dim_dynamic_wrap(%src: !tt.ptr<f32>, %dst: !tt.ptr<f32>, %idx_dyn: tensor<?xi32>, %mask_dyn: tensor<?xi1>, %n: i32) {
    %c0 = arith.constant 0 : i32
    %c1 = arith.constant 1 : i32
    %idx0 = arith.constant dense<[0, 1]> : tensor<2xi32>
    %mask0 = arith.constant dense<[true, false]> : tensor<2xi1>

    %src_base = tta.make_addr %src to sizes: [2, 4], strides: [4, 1], offsets: [1, 3], wrap_boundaries: [5, 9], layout: "strided" : <f32> to !tta.addr<f32, 2, 1>
    %src_seed = "tta.indirect_reindex"(%src_base, %idx0, %mask0) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 2, 1>, tensor<2xi32>, tensor<2xi1>) -> !tta.addr<f32, 2, 1>
    %dst_addr0 = tta.make_addr %dst to sizes: [2, 4], strides: [4, 1], offsets: [0, 2], wrap_boundaries: [7, 11], layout: "strided" : <f32> to !tta.addr<f32, 2, 1>

    %res:2 = scf.for %iv = %c0 to %n step %c1 iter_args(%src_addr = %src_seed, %dst_addr = %dst_addr0) -> (!tta.addr<f32, 2, 1>, !tta.addr<f32, 2, 1>) : i32 {
      %val = "tta.load"(%src_addr) <{operandSegmentSizes = array<i32: 1, 0, 0>, static_mask_dims = array<i64>}> : (!tta.addr<f32, 2, 1>) -> tensor<2x4xf32>
      "tta.store"(%dst_addr, %val) <{static_mask_dims = array<i64>}> : (!tta.addr<f32, 2, 1>, tensor<2x4xf32>) -> ()
      %next_src0 = "tta.indirect_reindex"(%src_addr, %idx0, %mask0) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 2, 1>, tensor<2xi32>, tensor<2xi1>) -> !tta.addr<f32, 2, 1>
      %next_src1 = "tta.indirect_reindex"(%next_src0, %idx_dyn, %mask_dyn) <{indirect_dim = 1 : i32}> : (!tta.addr<f32, 2, 1>, tensor<?xi32>, tensor<?xi1>) -> !tta.addr<f32, 2, 1>
      %next_dst = "tta.advance"(%dst_addr) <{static_deltas = array<i64: 0, 1>}> : (!tta.addr<f32, 2, 1>) -> !tta.addr<f32, 2, 1>
      scf.yield %next_src1, %next_dst : !tta.addr<f32, 2, 1>, !tta.addr<f32, 2, 1>
    }
    tt.return
  }
}

// -----

module {
// CHECK-LABEL:   tt.func @loop_carried_addr_supported_indirect_recurrence_multi_dim_same_dim_step_merge(
// CHECK-SAME:      %[[ARG0:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG1:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG2:[-0-9A-Za-z$._]+]]: i32) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant dense<[0, 1]> : tensor<2xindex>
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 1 : index
// CHECK:           %[[CONSTANT_2:.*]] = arith.constant 4 : index
// CHECK:           %[[CONSTANT_3:.*]] = arith.constant 2 : index
// CHECK:           %[[CONSTANT_4:.*]] = arith.constant dense<[0, 1, 2, 3]> : tensor<4xindex>
// CHECK:           %[[CONSTANT_5:.*]] = arith.constant 0 : index
// CHECK:           %[[CONSTANT_6:.*]] = arith.constant 0 : i32
// CHECK:           %[[CONSTANT_7:.*]] = arith.constant 1 : i32
// CHECK:           %[[CONSTANT_8:.*]] = arith.constant dense<[0, 1]> : tensor<2xi32>
// CHECK:           %[[CONSTANT_9:.*]] = arith.constant dense<[1, 0]> : tensor<2xi32>
// CHECK:           %[[CONSTANT_10:.*]] = arith.constant dense<[0, 1, 2, 3]> : tensor<4xi32>
// CHECK:           %[[CONSTANT_11:.*]] = arith.constant dense<[true, false]> : tensor<2xi1>
// CHECK:           %[[CONSTANT_12:.*]] = arith.constant dense<true> : tensor<2xi1>
// CHECK:           %[[MAKE_ADDR_0:.*]] = tta.make_addr %[[ARG0]] to sizes: [2, 4], strides: [4, 1], offsets: [0, 0], wrap_boundaries: [0, 0], layout: "strided" : <f32> to !tta.addr<f32, 2, 1>
// CHECK:           %[[VAL_0:.*]] = "tta.indirect_reindex"(%[[MAKE_ADDR_0]], %[[CONSTANT_8]], %[[CONSTANT_11]]) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 2, 1>, tensor<2xi32>, tensor<2xi1>) -> !tta.addr<f32, 2, 1>
// CHECK:           %[[MAKE_ADDR_1:.*]] = tta.make_addr %[[ARG1]] to sizes: [2, 4], strides: [4, 1], offsets: [0, 0], wrap_boundaries: [0, 0], layout: "strided" : <f32> to !tta.addr<f32, 2, 1>
// CHECK:           %[[FOR_0:.*]]:2 = scf.for %[[VAL_1:.*]] = %[[CONSTANT_6]] to %[[ARG2]] step %[[CONSTANT_7]] iter_args(%[[VAL_2:.*]] = %[[VAL_0]], %[[VAL_3:.*]] = %[[MAKE_ADDR_1]]) -> (!tta.addr<f32, 2, 1>, !tta.addr<f32, 2, 1>)  : i32 {
// CHECK:             %[[INDEX_CAST_0:.*]] = arith.index_cast %[[VAL_1]] : i32 to index
// CHECK:             %[[CMPI_0:.*]] = arith.cmpi eq, %[[INDEX_CAST_0]], %[[CONSTANT_5]] : index
// CHECK:             %[[SPLAT_0:.*]] = tensor.splat %[[INDEX_CAST_0]] : tensor<2xindex>
// CHECK:             %[[ADDI_0:.*]] = arith.addi %[[SPLAT_0]], %[[CONSTANT_0]] : tensor<2xindex>
// CHECK:             %[[SPLAT_1:.*]] = tensor.splat %[[INDEX_CAST_0]] : tensor<4xindex>
// CHECK:             %[[MULI_0:.*]] = arith.muli %[[SPLAT_1]], %[[CONSTANT_4]] : tensor<4xindex>
// CHECK:             %[[SELECT_0:.*]] = arith.select %[[CMPI_0]], %[[CONSTANT_4]], %[[MULI_0]] : tensor<4xindex>
// CHECK:             %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:             %[[ALLOC_0:.*]] = memref.alloc() : memref<2x4xf32>
// CHECK:             %[[CAST_0:.*]] = memref.cast %[[UNREALIZED_CONVERSION_CAST_0]] : memref<*xf32> to memref<?xf32>
// CHECK:             scf.for %[[VAL_4:.*]] = %[[CONSTANT_5]] to %[[CONSTANT_3]] step %[[CONSTANT_1]] {
// CHECK:               scf.for %[[VAL_5:.*]] = %[[CONSTANT_5]] to %[[CONSTANT_2]] step %[[CONSTANT_1]] {
// CHECK:                 %[[EXTRACT_0:.*]] = tensor.extract %[[CONSTANT_11]]{{\[}}%[[VAL_4]]] : tensor<2xi1>
// CHECK:                 scf.if %[[EXTRACT_0]] {
// CHECK:                   %[[EXTRACT_1:.*]] = tensor.extract %[[ADDI_0]]{{\[}}%[[VAL_4]]] : tensor<2xindex>
// CHECK:                   %[[MULI_1:.*]] = arith.muli %[[EXTRACT_1]], %[[CONSTANT_2]] : index
// CHECK:                   %[[EXTRACT_2:.*]] = tensor.extract %[[SELECT_0]]{{\[}}%[[VAL_5]]] : tensor<4xindex>
// CHECK:                   %[[ADDI_1:.*]] = arith.addi %[[MULI_1]], %[[EXTRACT_2]] : index
// CHECK:                   %[[LOAD_0:.*]] = memref.load %[[CAST_0]]{{\[}}%[[ADDI_1]]] : memref<?xf32>
// CHECK:                   memref.store %[[LOAD_0]], %[[ALLOC_0]]{{\[}}%[[VAL_4]], %[[VAL_5]]] : memref<2x4xf32>
// CHECK:                 }
// CHECK:               }
// CHECK:             }
// CHECK:             %[[TO_TENSOR_0:.*]] = bufferization.to_tensor %[[ALLOC_0]] restrict writable : memref<2x4xf32> to tensor<2x4xf32>
// CHECK:             %[[UNREALIZED_CONVERSION_CAST_1:.*]] = builtin.unrealized_conversion_cast %[[ARG1]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:             %[[REINTERPRET_CAST_0:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_1]] to offset: {{\[}}%[[INDEX_CAST_0]]], sizes: [2, 4], strides: [4, 1] : memref<*xf32> to memref<2x4xf32, strided<[4, 1], offset: ?>>
// CHECK:             bufferization.materialize_in_destination %[[TO_TENSOR_0]] in writable %[[REINTERPRET_CAST_0]] : (tensor<2x4xf32>, memref<2x4xf32, strided<[4, 1], offset: ?>>) -> ()
// CHECK:             %[[VAL_6:.*]] = "tta.indirect_reindex"(%[[VAL_2]], %[[CONSTANT_8]], %[[CONSTANT_11]]) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 2, 1>, tensor<2xi32>, tensor<2xi1>) -> !tta.addr<f32, 2, 1>
// CHECK:             %[[VAL_7:.*]] = "tta.indirect_reindex"(%[[VAL_6]], %[[CONSTANT_9]], %[[CONSTANT_12]]) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 2, 1>, tensor<2xi32>, tensor<2xi1>) -> !tta.addr<f32, 2, 1>
// CHECK:             %[[VAL_8:.*]] = "tta.indirect_reindex"(%[[VAL_7]], %[[CONSTANT_10]]) <{indirect_dim = 1 : i32}> : (!tta.addr<f32, 2, 1>, tensor<4xi32>) -> !tta.addr<f32, 2, 1>
// CHECK:             %[[VAL_9:.*]] = "tta.advance"(%[[VAL_3]]) <{static_deltas = array<i64: 1, 0>}> : (!tta.addr<f32, 2, 1>) -> !tta.addr<f32, 2, 1>
// CHECK:             scf.yield %[[VAL_8]], %[[VAL_9]] : !tta.addr<f32, 2, 1>, !tta.addr<f32, 2, 1>
// CHECK:           }
// CHECK:           tt.return
// CHECK:         }
  tt.func @loop_carried_addr_supported_indirect_recurrence_multi_dim_same_dim_step_merge(%src: !tt.ptr<f32>, %dst: !tt.ptr<f32>, %n: i32) {
    %c0 = arith.constant 0 : i32
    %c1 = arith.constant 1 : i32
    %idx0_a = arith.constant dense<[0, 1]> : tensor<2xi32>
    %idx0_b = arith.constant dense<[1, 0]> : tensor<2xi32>
    %idx1 = arith.constant dense<[0, 1, 2, 3]> : tensor<4xi32>
    %mask0_a = arith.constant dense<[true, false]> : tensor<2xi1>
    %mask0_b = arith.constant dense<[true, true]> : tensor<2xi1>

    %src_base = tta.make_addr %src to sizes: [2, 4], strides: [4, 1], offsets: [0, 0], wrap_boundaries: [0, 0], layout: "strided" : <f32> to !tta.addr<f32, 2, 1>
    %src_seed = "tta.indirect_reindex"(%src_base, %idx0_a, %mask0_a) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 2, 1>, tensor<2xi32>, tensor<2xi1>) -> !tta.addr<f32, 2, 1>
    %dst_addr0 = tta.make_addr %dst to sizes: [2, 4], strides: [4, 1], offsets: [0, 0], wrap_boundaries: [0, 0], layout: "strided" : <f32> to !tta.addr<f32, 2, 1>

    %res:2 = scf.for %iv = %c0 to %n step %c1 iter_args(%src_addr = %src_seed, %dst_addr = %dst_addr0) -> (!tta.addr<f32, 2, 1>, !tta.addr<f32, 2, 1>) : i32 {
      %val = "tta.load"(%src_addr) <{operandSegmentSizes = array<i32: 1, 0, 0>, static_mask_dims = array<i64>}> : (!tta.addr<f32, 2, 1>) -> tensor<2x4xf32>
      "tta.store"(%dst_addr, %val) <{static_mask_dims = array<i64>}> : (!tta.addr<f32, 2, 1>, tensor<2x4xf32>) -> ()
      %next_src0 = "tta.indirect_reindex"(%src_addr, %idx0_a, %mask0_a) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 2, 1>, tensor<2xi32>, tensor<2xi1>) -> !tta.addr<f32, 2, 1>
      %next_src1 = "tta.indirect_reindex"(%next_src0, %idx0_b, %mask0_b) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 2, 1>, tensor<2xi32>, tensor<2xi1>) -> !tta.addr<f32, 2, 1>
      %next_src2 = "tta.indirect_reindex"(%next_src1, %idx1) <{indirect_dim = 1 : i32}> : (!tta.addr<f32, 2, 1>, tensor<4xi32>) -> !tta.addr<f32, 2, 1>
      %next_dst = "tta.advance"(%dst_addr) <{static_deltas = array<i64: 1, 0>}> : (!tta.addr<f32, 2, 1>) -> !tta.addr<f32, 2, 1>
      scf.yield %next_src2, %next_dst : !tta.addr<f32, 2, 1>, !tta.addr<f32, 2, 1>
    }
    tt.return
  }
}

// -----

module {
// CHECK-LABEL:   tt.func @indirect_non_zero_offset(
// CHECK-SAME:      %[[ARG0:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG1:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant dense<[0, 1, 2, 3]> : tensor<4xindex>
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 1 : index
// CHECK:           %[[CONSTANT_2:.*]] = arith.constant 0 : index
// CHECK:           %[[CONSTANT_3:.*]] = arith.constant 4 : index
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:           %[[ALLOC_0:.*]] = memref.alloc() : memref<4xf32>
// CHECK:           scf.for %[[VAL_0:.*]] = %[[CONSTANT_2]] to %[[CONSTANT_3]] step %[[CONSTANT_1]] {
// CHECK:             %[[EXTRACT_0:.*]] = tensor.extract %[[CONSTANT_0]]{{\[}}%[[VAL_0]]] : tensor<4xindex>
// CHECK:             %[[ADDI_0:.*]] = arith.addi %[[EXTRACT_0]], %[[CONSTANT_1]] : index
// CHECK:             %[[REINTERPRET_CAST_0:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_0]] to offset: {{\[}}%[[ADDI_0]]], sizes: [1], strides: [1] : memref<*xf32> to memref<1xf32, strided<[1], offset: ?>>
// CHECK:             %[[SUBVIEW_0:.*]] = memref.subview %[[ALLOC_0]]{{\[}}%[[VAL_0]]] [1] [1] : memref<4xf32> to memref<1xf32, strided<[1], offset: ?>>
// CHECK:             memref.copy %[[REINTERPRET_CAST_0]], %[[SUBVIEW_0]] : memref<1xf32, strided<[1], offset: ?>> to memref<1xf32, strided<[1], offset: ?>>
// CHECK:           }
// CHECK:           %[[TO_TENSOR_0:.*]] = bufferization.to_tensor %[[ALLOC_0]] restrict writable : memref<4xf32> to tensor<4xf32>
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_1:.*]] = builtin.unrealized_conversion_cast %[[ARG1]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:           scf.for %[[VAL_1:.*]] = %[[CONSTANT_2]] to %[[CONSTANT_3]] step %[[CONSTANT_1]] {
// CHECK:             %[[EXTRACT_1:.*]] = tensor.extract %[[CONSTANT_0]]{{\[}}%[[VAL_1]]] : tensor<4xindex>
// CHECK:             %[[ADDI_1:.*]] = arith.addi %[[EXTRACT_1]], %[[CONSTANT_1]] : index
// CHECK:             %[[REINTERPRET_CAST_1:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_1]] to offset: {{\[}}%[[ADDI_1]]], sizes: [1], strides: [1] : memref<*xf32> to memref<1xf32, strided<[1], offset: ?>>
// CHECK:             %[[EXTRACT_SLICE_0:.*]] = tensor.extract_slice %[[TO_TENSOR_0]]{{\[}}%[[VAL_1]]] [1] [1] : tensor<4xf32> to tensor<1xf32>
// CHECK:             bufferization.materialize_in_destination %[[EXTRACT_SLICE_0]] in writable %[[REINTERPRET_CAST_1]] : (tensor<1xf32>, memref<1xf32, strided<[1], offset: ?>>) -> ()
// CHECK:           }
// CHECK:           tt.return
// CHECK:         }
  tt.func @indirect_non_zero_offset(%src: !tt.ptr<f32>, %dst: !tt.ptr<f32>) {
    %offsets = arith.constant dense<[0, 1, 2, 3]> : tensor<4xi32>

    %src_addr = tta.make_addr %src to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
    %src_off = "tta.reindex"(%src_addr) <{static_offsets = array<i64: 1>}> : (!tta.addr<f32, 1, 1>) -> !tta.addr<f32, 1, 1>
    %src_idx = "tta.indirect_reindex"(%src_off, %offsets) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 1, 1>, tensor<4xi32>) -> !tta.addr<f32, 1, 1>
    %val = "tta.load"(%src_idx) <{operandSegmentSizes = array<i32: 1, 0, 0>, static_mask_dims = array<i64>}> : (!tta.addr<f32, 1, 1>) -> tensor<4xf32>

    %dst_addr = tta.make_addr %dst to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
    %dst_off = "tta.reindex"(%dst_addr) <{static_offsets = array<i64: 1>}> : (!tta.addr<f32, 1, 1>) -> !tta.addr<f32, 1, 1>
    %dst_idx = "tta.indirect_reindex"(%dst_off, %offsets) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 1, 1>, tensor<4xi32>) -> !tta.addr<f32, 1, 1>
    "tta.store"(%dst_idx, %val) <{static_mask_dims = array<i64>}> : (!tta.addr<f32, 1, 1>, tensor<4xf32>) -> ()
    tt.return
  }
}

// -----

module {
// CHECK-LABEL:   tt.func @chained_indirect_same_dim(
// CHECK-SAME:      %[[ARG0:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG1:[-0-9A-Za-z$._]+]]: tensor<4xi32>,
// CHECK-SAME:      %[[ARG2:[-0-9A-Za-z$._]+]]: tensor<4xi32>,
// CHECK-SAME:      %[[ARG3:[-0-9A-Za-z$._]+]]: tensor<4xi1>,
// CHECK-SAME:      %[[ARG4:[-0-9A-Za-z$._]+]]: tensor<4xi1>) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 1 : index
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 0 : index
// CHECK:           %[[CONSTANT_2:.*]] = arith.constant 4 : index
// CHECK:           %[[INDEX_CAST_0:.*]] = arith.index_cast %[[ARG1]] : tensor<4xi32> to tensor<4xindex>
// CHECK:           %[[INDEX_CAST_1:.*]] = arith.index_cast %[[ARG2]] : tensor<4xi32> to tensor<4xindex>
// CHECK:           %[[ADDI_0:.*]] = arith.addi %[[INDEX_CAST_0]], %[[INDEX_CAST_1]] : tensor<4xindex>
// CHECK:           %[[ANDI_0:.*]] = arith.andi %[[ARG3]], %[[ARG4]] : tensor<4xi1>
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:           %[[ALLOC_0:.*]] = memref.alloc() : memref<4xf32>
// CHECK:           scf.for %[[VAL_0:.*]] = %[[CONSTANT_1]] to %[[CONSTANT_2]] step %[[CONSTANT_0]] {
// CHECK:             %[[EXTRACT_0:.*]] = tensor.extract %[[ANDI_0]]{{\[}}%[[VAL_0]]] : tensor<4xi1>
// CHECK:             scf.if %[[EXTRACT_0]] {
// CHECK:               %[[EXTRACT_1:.*]] = tensor.extract %[[ADDI_0]]{{\[}}%[[VAL_0]]] : tensor<4xindex>
// CHECK:               %[[REINTERPRET_CAST_0:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_0]] to offset: {{\[}}%[[EXTRACT_1]]], sizes: [1], strides: [1] : memref<*xf32> to memref<1xf32, strided<[1], offset: ?>>
// CHECK:               %[[SUBVIEW_0:.*]] = memref.subview %[[ALLOC_0]]{{\[}}%[[VAL_0]]] [1] [1] : memref<4xf32> to memref<1xf32, strided<[1], offset: ?>>
// CHECK:               memref.copy %[[REINTERPRET_CAST_0]], %[[SUBVIEW_0]] : memref<1xf32, strided<[1], offset: ?>> to memref<1xf32, strided<[1], offset: ?>>
// CHECK:             }
// CHECK:           }
// CHECK:           %[[TO_TENSOR_0:.*]] = bufferization.to_tensor %[[ALLOC_0]] restrict writable : memref<4xf32> to tensor<4xf32>
// CHECK:           scf.for %[[VAL_1:.*]] = %[[CONSTANT_1]] to %[[CONSTANT_2]] step %[[CONSTANT_0]] {
// CHECK:             %[[EXTRACT_2:.*]] = tensor.extract %[[ANDI_0]]{{\[}}%[[VAL_1]]] : tensor<4xi1>
// CHECK:             scf.if %[[EXTRACT_2]] {
// CHECK:               %[[EXTRACT_3:.*]] = tensor.extract %[[ADDI_0]]{{\[}}%[[VAL_1]]] : tensor<4xindex>
// CHECK:               %[[REINTERPRET_CAST_1:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_0]] to offset: {{\[}}%[[EXTRACT_3]]], sizes: [1], strides: [1] : memref<*xf32> to memref<1xf32, strided<[1], offset: ?>>
// CHECK:               %[[EXTRACT_SLICE_0:.*]] = tensor.extract_slice %[[TO_TENSOR_0]]{{\[}}%[[VAL_1]]] [1] [1] : tensor<4xf32> to tensor<1xf32>
// CHECK:               bufferization.materialize_in_destination %[[EXTRACT_SLICE_0]] in writable %[[REINTERPRET_CAST_1]] : (tensor<1xf32>, memref<1xf32, strided<[1], offset: ?>>) -> ()
// CHECK:             }
// CHECK:           }
// CHECK:           tt.return
// CHECK:         }
  tt.func @chained_indirect_same_dim(%src: !tt.ptr<f32>, %idx0: tensor<4xi32>, %idx1: tensor<4xi32>, %mask0: tensor<4xi1>, %mask1: tensor<4xi1>) {
    %addr = tta.make_addr %src to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
    %r0 = "tta.indirect_reindex"(%addr, %idx0, %mask0) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 1, 1>, tensor<4xi32>, tensor<4xi1>) -> !tta.addr<f32, 1, 1>
    %r1 = "tta.indirect_reindex"(%r0, %idx1, %mask1) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 1, 1>, tensor<4xi32>, tensor<4xi1>) -> !tta.addr<f32, 1, 1>
    %val = "tta.load"(%r1) <{operandSegmentSizes = array<i32: 1, 0, 0>, static_mask_dims = array<i64>}> : (!tta.addr<f32, 1, 1>) -> tensor<4xf32>

    %out_addr = tta.make_addr %src to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
    %out_r0 = "tta.indirect_reindex"(%out_addr, %idx0, %mask0) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 1, 1>, tensor<4xi32>, tensor<4xi1>) -> !tta.addr<f32, 1, 1>
    %out_r1 = "tta.indirect_reindex"(%out_r0, %idx1, %mask1) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 1, 1>, tensor<4xi32>, tensor<4xi1>) -> !tta.addr<f32, 1, 1>
    "tta.store"(%out_r1, %val) <{static_mask_dims = array<i64>}> : (!tta.addr<f32, 1, 1>, tensor<4xf32>) -> ()
    tt.return
  }
}

// -----

module {
// CHECK-LABEL:   tt.func @chained_indirect_dynamic_static_dim(
// CHECK-SAME:      %[[ARG0:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG1:[-0-9A-Za-z$._]+]]: tensor<?xi32>,
// CHECK-SAME:      %[[ARG2:[-0-9A-Za-z$._]+]]: tensor<4xi32>,
// CHECK-SAME:      %[[ARG3:[-0-9A-Za-z$._]+]]: tensor<?xi1>,
// CHECK-SAME:      %[[ARG4:[-0-9A-Za-z$._]+]]: tensor<4xi1>) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 1 : index
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 4 : index
// CHECK:           %[[CONSTANT_2:.*]] = arith.constant 0 : index
// CHECK:           %[[INDEX_CAST_0:.*]] = arith.index_cast %[[ARG1]] : tensor<?xi32> to tensor<?xindex>
// CHECK:           %[[INDEX_CAST_1:.*]] = arith.index_cast %[[ARG2]] : tensor<4xi32> to tensor<4xindex>
// CHECK:           %[[CAST_0:.*]] = tensor.cast %[[INDEX_CAST_1]] : tensor<4xindex> to tensor<?xindex>
// CHECK:           %[[ADDI_0:.*]] = arith.addi %[[INDEX_CAST_0]], %[[CAST_0]] : tensor<?xindex>
// CHECK:           %[[CAST_1:.*]] = tensor.cast %[[ARG4]] : tensor<4xi1> to tensor<?xi1>
// CHECK:           %[[ANDI_0:.*]] = arith.andi %[[ARG3]], %[[CAST_1]] : tensor<?xi1>
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:           %[[ALLOC_0:.*]] = memref.alloc() : memref<4xf32>
// CHECK:           %[[DIM_0:.*]] = tensor.dim %[[ADDI_0]], %[[CONSTANT_2]] : tensor<?xindex>
// CHECK:           %[[MINSI_0:.*]] = arith.minsi %[[DIM_0]], %[[CONSTANT_1]] : index
// CHECK:           scf.for %[[VAL_0:.*]] = %[[CONSTANT_2]] to %[[MINSI_0]] step %[[CONSTANT_0]] {
// CHECK:             %[[EXTRACT_0:.*]] = tensor.extract %[[ANDI_0]]{{\[}}%[[VAL_0]]] : tensor<?xi1>
// CHECK:             scf.if %[[EXTRACT_0]] {
// CHECK:               %[[EXTRACT_1:.*]] = tensor.extract %[[ADDI_0]]{{\[}}%[[VAL_0]]] : tensor<?xindex>
// CHECK:               %[[REINTERPRET_CAST_0:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_0]] to offset: {{\[}}%[[EXTRACT_1]]], sizes: [1], strides: [1] : memref<*xf32> to memref<1xf32, strided<[1], offset: ?>>
// CHECK:               %[[SUBVIEW_0:.*]] = memref.subview %[[ALLOC_0]]{{\[}}%[[VAL_0]]] [1] [1] : memref<4xf32> to memref<1xf32, strided<[1], offset: ?>>
// CHECK:               memref.copy %[[REINTERPRET_CAST_0]], %[[SUBVIEW_0]] : memref<1xf32, strided<[1], offset: ?>> to memref<1xf32, strided<[1], offset: ?>>
// CHECK:             }
// CHECK:           }
// CHECK:           %[[TO_TENSOR_0:.*]] = bufferization.to_tensor %[[ALLOC_0]] restrict writable : memref<4xf32> to tensor<4xf32>
// CHECK:           scf.for %[[VAL_1:.*]] = %[[CONSTANT_2]] to %[[MINSI_0]] step %[[CONSTANT_0]] {
// CHECK:             %[[EXTRACT_2:.*]] = tensor.extract %[[ANDI_0]]{{\[}}%[[VAL_1]]] : tensor<?xi1>
// CHECK:             scf.if %[[EXTRACT_2]] {
// CHECK:               %[[EXTRACT_3:.*]] = tensor.extract %[[ADDI_0]]{{\[}}%[[VAL_1]]] : tensor<?xindex>
// CHECK:               %[[REINTERPRET_CAST_1:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_0]] to offset: {{\[}}%[[EXTRACT_3]]], sizes: [1], strides: [1] : memref<*xf32> to memref<1xf32, strided<[1], offset: ?>>
// CHECK:               %[[EXTRACT_SLICE_0:.*]] = tensor.extract_slice %[[TO_TENSOR_0]]{{\[}}%[[VAL_1]]] [1] [1] : tensor<4xf32> to tensor<1xf32>
// CHECK:               bufferization.materialize_in_destination %[[EXTRACT_SLICE_0]] in writable %[[REINTERPRET_CAST_1]] : (tensor<1xf32>, memref<1xf32, strided<[1], offset: ?>>) -> ()
// CHECK:             }
// CHECK:           }
// CHECK:           tt.return
// CHECK:         }
  tt.func @chained_indirect_dynamic_static_dim(%src: !tt.ptr<f32>, %idx_dyn: tensor<?xi32>, %idx_static: tensor<4xi32>, %mask_dyn: tensor<?xi1>, %mask_static: tensor<4xi1>) {
    %addr = tta.make_addr %src to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
    %r0 = "tta.indirect_reindex"(%addr, %idx_dyn, %mask_dyn) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 1, 1>, tensor<?xi32>, tensor<?xi1>) -> !tta.addr<f32, 1, 1>
    %r1 = "tta.indirect_reindex"(%r0, %idx_static, %mask_static) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 1, 1>, tensor<4xi32>, tensor<4xi1>) -> !tta.addr<f32, 1, 1>
    %val = "tta.load"(%r1) <{operandSegmentSizes = array<i32: 1, 0, 0>, static_mask_dims = array<i64>}> : (!tta.addr<f32, 1, 1>) -> tensor<4xf32>

    %out_addr = tta.make_addr %src to sizes: [4], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
    %out_r0 = "tta.indirect_reindex"(%out_addr, %idx_dyn, %mask_dyn) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 1, 1>, tensor<?xi32>, tensor<?xi1>) -> !tta.addr<f32, 1, 1>
    %out_r1 = "tta.indirect_reindex"(%out_r0, %idx_static, %mask_static) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 1, 1>, tensor<4xi32>, tensor<4xi1>) -> !tta.addr<f32, 1, 1>
    "tta.store"(%out_r1, %val) <{static_mask_dims = array<i64>}> : (!tta.addr<f32, 1, 1>, tensor<4xf32>) -> ()
    tt.return
  }
}

// -----

module {
// CHECK-LABEL:   tt.func @indirect_reindex_dim1_load_store(
// CHECK-SAME:      %[[ARG0:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG1:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant dense<[0, 1, 2, 3]> : tensor<4xindex>
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 1 : index
// CHECK:           %[[CONSTANT_2:.*]] = arith.constant 0 : index
// CHECK:           %[[CONSTANT_3:.*]] = arith.constant 4 : index
// CHECK:           %[[CONSTANT_4:.*]] = arith.constant 0.000000e+00 : f32
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:           %[[ALLOC_0:.*]] = memref.alloc() : memref<2x4xf32>
// CHECK:           linalg.fill ins(%[[CONSTANT_4]] : f32) outs(%[[ALLOC_0]] : memref<2x4xf32>)
// CHECK:           scf.for %[[VAL_0:.*]] = %[[CONSTANT_2]] to %[[CONSTANT_3]] step %[[CONSTANT_1]] {
// CHECK:             %[[EXTRACT_0:.*]] = tensor.extract %[[CONSTANT_0]]{{\[}}%[[VAL_0]]] : tensor<4xindex>
// CHECK:             %[[REINTERPRET_CAST_0:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_0]] to offset: {{\[}}%[[EXTRACT_0]]], sizes: [2, 1], strides: [4, 1] : memref<*xf32> to memref<2x1xf32, strided<[4, 1], offset: ?>>
// CHECK:             %[[SUBVIEW_0:.*]] = memref.subview %[[ALLOC_0]][0, %[[VAL_0]]] [2, 1] [1, 1] : memref<2x4xf32> to memref<2x1xf32, strided<[4, 1], offset: ?>>
// CHECK:             memref.copy %[[REINTERPRET_CAST_0]], %[[SUBVIEW_0]] : memref<2x1xf32, strided<[4, 1], offset: ?>> to memref<2x1xf32, strided<[4, 1], offset: ?>>
// CHECK:           }
// CHECK:           %[[TO_TENSOR_0:.*]] = bufferization.to_tensor %[[ALLOC_0]] restrict writable : memref<2x4xf32> to tensor<2x4xf32>
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_1:.*]] = builtin.unrealized_conversion_cast %[[ARG1]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:           scf.for %[[VAL_1:.*]] = %[[CONSTANT_2]] to %[[CONSTANT_3]] step %[[CONSTANT_1]] {
// CHECK:             %[[EXTRACT_1:.*]] = tensor.extract %[[CONSTANT_0]]{{\[}}%[[VAL_1]]] : tensor<4xindex>
// CHECK:             %[[REINTERPRET_CAST_1:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_1]] to offset: {{\[}}%[[EXTRACT_1]]], sizes: [2, 1], strides: [4, 1] : memref<*xf32> to memref<2x1xf32, strided<[4, 1], offset: ?>>
// CHECK:             %[[EXTRACT_SLICE_0:.*]] = tensor.extract_slice %[[TO_TENSOR_0]][0, %[[VAL_1]]] [2, 1] [1, 1] : tensor<2x4xf32> to tensor<2x1xf32>
// CHECK:             bufferization.materialize_in_destination %[[EXTRACT_SLICE_0]] in writable %[[REINTERPRET_CAST_1]] : (tensor<2x1xf32>, memref<2x1xf32, strided<[4, 1], offset: ?>>) -> ()
// CHECK:           }
// CHECK:           tt.return
// CHECK:         }
  tt.func @indirect_reindex_dim1_load_store(%src: !tt.ptr<f32>, %dst: !tt.ptr<f32>) {
    %idx = arith.constant dense<[0, 1, 2, 3]> : tensor<4xi32>
    %src_addr = tta.make_addr %src to sizes: [2, 4], strides: [4, 1], offsets: [0, 0], wrap_boundaries: [0, 0], layout: "strided" : <f32> to !tta.addr<f32, 2, 1>
    %src_idx = "tta.indirect_reindex"(%src_addr, %idx) <{indirect_dim = 1 : i32}> : (!tta.addr<f32, 2, 1>, tensor<4xi32>) -> !tta.addr<f32, 2, 1>
    %other = arith.constant 0.0 : f32
    %val = "tta.load"(%src_idx, %other) <{operandSegmentSizes = array<i32: 1, 0, 1>, static_mask_dims = array<i64>}> : (!tta.addr<f32, 2, 1>, f32) -> tensor<2x4xf32>

    %dst_addr = tta.make_addr %dst to sizes: [2, 4], strides: [4, 1], offsets: [0, 0], wrap_boundaries: [0, 0], layout: "strided" : <f32> to !tta.addr<f32, 2, 1>
    %dst_idx = "tta.indirect_reindex"(%dst_addr, %idx) <{indirect_dim = 1 : i32}> : (!tta.addr<f32, 2, 1>, tensor<4xi32>) -> !tta.addr<f32, 2, 1>
    "tta.store"(%dst_idx, %val) <{static_mask_dims = array<i64>}> : (!tta.addr<f32, 2, 1>, tensor<2x4xf32>) -> ()
    tt.return
  }
}

// -----

module {
// CHECK-LABEL:   tt.func @indirect_reindex_multi_dim_load_store(
// CHECK-SAME:      %[[ARG0:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG1:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant dense<[0, 1, 2, 3]> : tensor<4xindex>
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant dense<[0, 1]> : tensor<2xindex>
// CHECK:           %[[CONSTANT_2:.*]] = arith.constant 1 : index
// CHECK:           %[[CONSTANT_3:.*]] = arith.constant 0 : index
// CHECK:           %[[CONSTANT_4:.*]] = arith.constant 4 : index
// CHECK:           %[[CONSTANT_5:.*]] = arith.constant 2 : index
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:           %[[ALLOC_0:.*]] = memref.alloc() : memref<2x4xf32>
// CHECK:           %[[CAST_0:.*]] = memref.cast %[[UNREALIZED_CONVERSION_CAST_0]] : memref<*xf32> to memref<?xf32>
// CHECK:           scf.for %[[VAL_0:.*]] = %[[CONSTANT_3]] to %[[CONSTANT_5]] step %[[CONSTANT_2]] {
// CHECK:             scf.for %[[VAL_1:.*]] = %[[CONSTANT_3]] to %[[CONSTANT_4]] step %[[CONSTANT_2]] {
// CHECK:               %[[EXTRACT_0:.*]] = tensor.extract %[[CONSTANT_1]]{{\[}}%[[VAL_0]]] : tensor<2xindex>
// CHECK:               %[[MULI_0:.*]] = arith.muli %[[EXTRACT_0]], %[[CONSTANT_4]] : index
// CHECK:               %[[EXTRACT_1:.*]] = tensor.extract %[[CONSTANT_0]]{{\[}}%[[VAL_1]]] : tensor<4xindex>
// CHECK:               %[[ADDI_0:.*]] = arith.addi %[[MULI_0]], %[[EXTRACT_1]] : index
// CHECK:               %[[LOAD_0:.*]] = memref.load %[[CAST_0]]{{\[}}%[[ADDI_0]]] : memref<?xf32>
// CHECK:               memref.store %[[LOAD_0]], %[[ALLOC_0]]{{\[}}%[[VAL_0]], %[[VAL_1]]] : memref<2x4xf32>
// CHECK:             }
// CHECK:           }
// CHECK:           %[[TO_TENSOR_0:.*]] = bufferization.to_tensor %[[ALLOC_0]] restrict writable : memref<2x4xf32> to tensor<2x4xf32>
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_1:.*]] = builtin.unrealized_conversion_cast %[[ARG1]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:           %[[CAST_1:.*]] = memref.cast %[[UNREALIZED_CONVERSION_CAST_1]] : memref<*xf32> to memref<?xf32>
// CHECK:           scf.for %[[VAL_2:.*]] = %[[CONSTANT_3]] to %[[CONSTANT_5]] step %[[CONSTANT_2]] {
// CHECK:             scf.for %[[VAL_3:.*]] = %[[CONSTANT_3]] to %[[CONSTANT_4]] step %[[CONSTANT_2]] {
// CHECK:               %[[EXTRACT_2:.*]] = tensor.extract %[[CONSTANT_1]]{{\[}}%[[VAL_2]]] : tensor<2xindex>
// CHECK:               %[[MULI_1:.*]] = arith.muli %[[EXTRACT_2]], %[[CONSTANT_4]] : index
// CHECK:               %[[EXTRACT_3:.*]] = tensor.extract %[[CONSTANT_0]]{{\[}}%[[VAL_3]]] : tensor<4xindex>
// CHECK:               %[[ADDI_1:.*]] = arith.addi %[[MULI_1]], %[[EXTRACT_3]] : index
// CHECK:               %[[EXTRACT_4:.*]] = tensor.extract %[[TO_TENSOR_0]]{{\[}}%[[VAL_2]], %[[VAL_3]]] : tensor<2x4xf32>
// CHECK:               memref.store %[[EXTRACT_4]], %[[CAST_1]]{{\[}}%[[ADDI_1]]] : memref<?xf32>
// CHECK:             }
// CHECK:           }
// CHECK:           tt.return
// CHECK:         }
  tt.func @indirect_reindex_multi_dim_load_store(%src: !tt.ptr<f32>, %dst: !tt.ptr<f32>) {
    %offsets0 = arith.constant dense<[0, 1]> : tensor<2xi32>
    %offsets1 = arith.constant dense<[0, 1, 2, 3]> : tensor<4xi32>

    %src_addr = tta.make_addr %src to sizes: [2, 4], strides: [4, 1], offsets: [0, 0], wrap_boundaries: [0, 0], layout: "strided" : <f32> to !tta.addr<f32, 2, 1>
    %src_idx0 = "tta.indirect_reindex"(%src_addr, %offsets0) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 2, 1>, tensor<2xi32>) -> !tta.addr<f32, 2, 1>
    %src_idx1 = "tta.indirect_reindex"(%src_idx0, %offsets1) <{indirect_dim = 1 : i32}> : (!tta.addr<f32, 2, 1>, tensor<4xi32>) -> !tta.addr<f32, 2, 1>
    %val = "tta.load"(%src_idx1) <{operandSegmentSizes = array<i32: 1, 0, 0>, static_mask_dims = array<i64>}> : (!tta.addr<f32, 2, 1>) -> tensor<2x4xf32>

    %dst_addr = tta.make_addr %dst to sizes: [2, 4], strides: [4, 1], offsets: [0, 0], wrap_boundaries: [0, 0], layout: "strided" : <f32> to !tta.addr<f32, 2, 1>
    %dst_idx0 = "tta.indirect_reindex"(%dst_addr, %offsets0) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 2, 1>, tensor<2xi32>) -> !tta.addr<f32, 2, 1>
    %dst_idx1 = "tta.indirect_reindex"(%dst_idx0, %offsets1) <{indirect_dim = 1 : i32}> : (!tta.addr<f32, 2, 1>, tensor<4xi32>) -> !tta.addr<f32, 2, 1>
    "tta.store"(%dst_idx1, %val) <{static_mask_dims = array<i64>}> : (!tta.addr<f32, 2, 1>, tensor<2x4xf32>) -> ()
    tt.return
  }
}

// -----

module {
// CHECK-LABEL:   tt.func @wrap_multi_indirect_load_store(
// CHECK-SAME:      %[[ARG0:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG1:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant dense<[0, 1, 2, 3]> : tensor<4xindex>
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant dense<[0, 1]> : tensor<2xindex>
// CHECK:           %[[CONSTANT_2:.*]] = arith.constant 1 : index
// CHECK:           %[[CONSTANT_3:.*]] = arith.constant 0 : index
// CHECK:           %[[CONSTANT_4:.*]] = arith.constant 4 : index
// CHECK:           %[[CONSTANT_5:.*]] = arith.constant 2 : index
// CHECK:           %[[CONSTANT_6:.*]] = arith.constant 0.000000e+00 : f32
// CHECK:           %[[CONSTANT_7:.*]] = arith.constant dense<[true, false]> : tensor<2xi1>
// CHECK:           %[[CONSTANT_8:.*]] = arith.constant dense<[true, true, false, true]> : tensor<4xi1>
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:           %[[ALLOC_0:.*]] = memref.alloc() : memref<2x4xf32>
// CHECK:           linalg.fill ins(%[[CONSTANT_6]] : f32) outs(%[[ALLOC_0]] : memref<2x4xf32>)
// CHECK:           %[[CAST_0:.*]] = memref.cast %[[UNREALIZED_CONVERSION_CAST_0]] : memref<*xf32> to memref<?xf32>
// CHECK:           scf.for %[[VAL_0:.*]] = %[[CONSTANT_3]] to %[[CONSTANT_5]] step %[[CONSTANT_2]] {
// CHECK:             scf.for %[[VAL_1:.*]] = %[[CONSTANT_3]] to %[[CONSTANT_4]] step %[[CONSTANT_2]] {
// CHECK:               %[[EXTRACT_0:.*]] = tensor.extract %[[CONSTANT_7]]{{\[}}%[[VAL_0]]] : tensor<2xi1>
// CHECK:               %[[EXTRACT_1:.*]] = tensor.extract %[[CONSTANT_8]]{{\[}}%[[VAL_1]]] : tensor<4xi1>
// CHECK:               %[[ANDI_0:.*]] = arith.andi %[[EXTRACT_0]], %[[EXTRACT_1]] : i1
// CHECK:               scf.if %[[ANDI_0]] {
// CHECK:                 %[[EXTRACT_2:.*]] = tensor.extract %[[CONSTANT_1]]{{\[}}%[[VAL_0]]] : tensor<2xindex>
// CHECK:                 %[[MULI_0:.*]] = arith.muli %[[EXTRACT_2]], %[[CONSTANT_4]] : index
// CHECK:                 %[[EXTRACT_3:.*]] = tensor.extract %[[CONSTANT_0]]{{\[}}%[[VAL_1]]] : tensor<4xindex>
// CHECK:                 %[[ADDI_0:.*]] = arith.addi %[[EXTRACT_3]], %[[CONSTANT_2]] : index
// CHECK:                 %[[REMSI_0:.*]] = arith.remsi %[[ADDI_0]], %[[CONSTANT_4]] : index
// CHECK:                 %[[CMPI_0:.*]] = arith.cmpi slt, %[[REMSI_0]], %[[CONSTANT_3]] : index
// CHECK:                 %[[ADDI_1:.*]] = arith.addi %[[REMSI_0]], %[[CONSTANT_4]] : index
// CHECK:                 %[[SELECT_0:.*]] = arith.select %[[CMPI_0]], %[[ADDI_1]], %[[REMSI_0]] : index
// CHECK:                 %[[ADDI_2:.*]] = arith.addi %[[MULI_0]], %[[SELECT_0]] : index
// CHECK:                 %[[LOAD_0:.*]] = memref.load %[[CAST_0]]{{\[}}%[[ADDI_2]]] : memref<?xf32>
// CHECK:                 memref.store %[[LOAD_0]], %[[ALLOC_0]]{{\[}}%[[VAL_0]], %[[VAL_1]]] : memref<2x4xf32>
// CHECK:               }
// CHECK:             }
// CHECK:           }
// CHECK:           %[[TO_TENSOR_0:.*]] = bufferization.to_tensor %[[ALLOC_0]] restrict writable : memref<2x4xf32> to tensor<2x4xf32>
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_1:.*]] = builtin.unrealized_conversion_cast %[[ARG1]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:           %[[CAST_1:.*]] = memref.cast %[[UNREALIZED_CONVERSION_CAST_1]] : memref<*xf32> to memref<?xf32>
// CHECK:           scf.for %[[VAL_2:.*]] = %[[CONSTANT_3]] to %[[CONSTANT_5]] step %[[CONSTANT_2]] {
// CHECK:             scf.for %[[VAL_3:.*]] = %[[CONSTANT_3]] to %[[CONSTANT_4]] step %[[CONSTANT_2]] {
// CHECK:               %[[EXTRACT_4:.*]] = tensor.extract %[[CONSTANT_7]]{{\[}}%[[VAL_2]]] : tensor<2xi1>
// CHECK:               %[[EXTRACT_5:.*]] = tensor.extract %[[CONSTANT_8]]{{\[}}%[[VAL_3]]] : tensor<4xi1>
// CHECK:               %[[ANDI_1:.*]] = arith.andi %[[EXTRACT_4]], %[[EXTRACT_5]] : i1
// CHECK:               scf.if %[[ANDI_1]] {
// CHECK:                 %[[EXTRACT_6:.*]] = tensor.extract %[[CONSTANT_1]]{{\[}}%[[VAL_2]]] : tensor<2xindex>
// CHECK:                 %[[MULI_1:.*]] = arith.muli %[[EXTRACT_6]], %[[CONSTANT_4]] : index
// CHECK:                 %[[EXTRACT_7:.*]] = tensor.extract %[[CONSTANT_0]]{{\[}}%[[VAL_3]]] : tensor<4xindex>
// CHECK:                 %[[ADDI_3:.*]] = arith.addi %[[EXTRACT_7]], %[[CONSTANT_5]] : index
// CHECK:                 %[[REMSI_1:.*]] = arith.remsi %[[ADDI_3]], %[[CONSTANT_4]] : index
// CHECK:                 %[[CMPI_1:.*]] = arith.cmpi slt, %[[REMSI_1]], %[[CONSTANT_3]] : index
// CHECK:                 %[[ADDI_4:.*]] = arith.addi %[[REMSI_1]], %[[CONSTANT_4]] : index
// CHECK:                 %[[SELECT_1:.*]] = arith.select %[[CMPI_1]], %[[ADDI_4]], %[[REMSI_1]] : index
// CHECK:                 %[[ADDI_5:.*]] = arith.addi %[[MULI_1]], %[[SELECT_1]] : index
// CHECK:                 %[[EXTRACT_8:.*]] = tensor.extract %[[TO_TENSOR_0]]{{\[}}%[[VAL_2]], %[[VAL_3]]] : tensor<2x4xf32>
// CHECK:                 memref.store %[[EXTRACT_8]], %[[CAST_1]]{{\[}}%[[ADDI_5]]] : memref<?xf32>
// CHECK:               }
// CHECK:             }
// CHECK:           }
// CHECK:           tt.return
// CHECK:         }
  tt.func @wrap_multi_indirect_load_store(%src: !tt.ptr<f32>, %dst: !tt.ptr<f32>) {
    %idx0 = arith.constant dense<[0, 1]> : tensor<2xi32>
    %idx1 = arith.constant dense<[0, 1, 2, 3]> : tensor<4xi32>
    %mask0 = arith.constant dense<[true, false]> : tensor<2xi1>
    %mask1 = arith.constant dense<[true, true, false, true]> : tensor<4xi1>

    %src_addr = tta.make_addr %src to sizes: [2, 4], strides: [4, 1], offsets: [0, 1], wrap_boundaries: [0, 4], layout: "strided" : <f32> to !tta.addr<f32, 2, 1>
    %src_idx0 = "tta.indirect_reindex"(%src_addr, %idx0, %mask0) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 2, 1>, tensor<2xi32>, tensor<2xi1>) -> !tta.addr<f32, 2, 1>
    %src_idx1 = "tta.indirect_reindex"(%src_idx0, %idx1, %mask1) <{indirect_dim = 1 : i32}> : (!tta.addr<f32, 2, 1>, tensor<4xi32>, tensor<4xi1>) -> !tta.addr<f32, 2, 1>
    %other = arith.constant 0.0 : f32
    %val = "tta.load"(%src_idx1, %other) <{operandSegmentSizes = array<i32: 1, 0, 1>, static_mask_dims = array<i64>}> : (!tta.addr<f32, 2, 1>, f32) -> tensor<2x4xf32>

    %dst_addr = tta.make_addr %dst to sizes: [2, 4], strides: [4, 1], offsets: [0, 2], wrap_boundaries: [0, 4], layout: "strided" : <f32> to !tta.addr<f32, 2, 1>
    %dst_idx0 = "tta.indirect_reindex"(%dst_addr, %idx0, %mask0) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 2, 1>, tensor<2xi32>, tensor<2xi1>) -> !tta.addr<f32, 2, 1>
    %dst_idx1 = "tta.indirect_reindex"(%dst_idx0, %idx1, %mask1) <{indirect_dim = 1 : i32}> : (!tta.addr<f32, 2, 1>, tensor<4xi32>, tensor<4xi1>) -> !tta.addr<f32, 2, 1>
    "tta.store"(%dst_idx1, %val) <{static_mask_dims = array<i64>}> : (!tta.addr<f32, 2, 1>, tensor<2x4xf32>) -> ()
    tt.return
  }
}

// -----

module {
// CHECK-LABEL:   tt.func @wrap_boundary_no_wrap_fastpath(
// CHECK-SAME:      %[[ARG0:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG1:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 0.000000e+00 : f32
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:           %[[ALLOC_0:.*]] = memref.alloc() : memref<4xf32>
// CHECK:           %[[REINTERPRET_CAST_0:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_0]] to offset: [1], sizes: [4], strides: [1] : memref<*xf32> to memref<4xf32, strided<[1], offset: 1>>
// CHECK:           linalg.fill ins(%[[CONSTANT_0]] : f32) outs(%[[ALLOC_0]] : memref<4xf32>)
// CHECK:           memref.copy %[[REINTERPRET_CAST_0]], %[[ALLOC_0]] : memref<4xf32, strided<[1], offset: 1>> to memref<4xf32>
// CHECK:           %[[TO_TENSOR_0:.*]] = bufferization.to_tensor %[[ALLOC_0]] restrict writable : memref<4xf32> to tensor<4xf32>
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_1:.*]] = builtin.unrealized_conversion_cast %[[ARG1]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:           %[[REINTERPRET_CAST_1:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_1]] to offset: [2], sizes: [4], strides: [1] : memref<*xf32> to memref<4xf32, strided<[1], offset: 2>>
// CHECK:           bufferization.materialize_in_destination %[[TO_TENSOR_0]] in writable %[[REINTERPRET_CAST_1]] : (tensor<4xf32>, memref<4xf32, strided<[1], offset: 2>>) -> ()
// CHECK:           tt.return
// CHECK:         }
  tt.func @wrap_boundary_no_wrap_fastpath(%src: !tt.ptr<f32>, %dst: !tt.ptr<f32>) {
    %src_addr = tta.make_addr %src to sizes: [4], strides: [1], offsets: [1], wrap_boundaries: [16], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
    %other = arith.constant 0.0 : f32
    %val = "tta.load"(%src_addr, %other) <{operandSegmentSizes = array<i32: 1, 0, 1>, static_mask_dims = array<i64>}> : (!tta.addr<f32, 1, 1>, f32) -> tensor<4xf32>
    %dst_addr = tta.make_addr %dst to sizes: [4], strides: [1], offsets: [2], wrap_boundaries: [16], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
    "tta.store"(%dst_addr, %val) <{static_mask_dims = array<i64>}> : (!tta.addr<f32, 1, 1>, tensor<4xf32>) -> ()
    tt.return
  }
}

// -----

module {
// CHECK-LABEL:   tt.func @wrap_boundary_rank1_segmented_load_store(
// CHECK-SAME:      %[[ARG0:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG1:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>) {
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:           %[[ALLOC_0:.*]] = memref.alloc() : memref<4xf32>
// CHECK:           %[[REINTERPRET_CAST_0:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_0]] to offset: [6], sizes: [2], strides: [1] : memref<*xf32> to memref<2xf32, strided<[1], offset: 6>>
// CHECK:           %[[SUBVIEW_0:.*]] = memref.subview %[[ALLOC_0]][0] [2] [1] : memref<4xf32> to memref<2xf32, strided<[1]>>
// CHECK:           memref.copy %[[REINTERPRET_CAST_0]], %[[SUBVIEW_0]] : memref<2xf32, strided<[1], offset: 6>> to memref<2xf32, strided<[1]>>
// CHECK:           %[[REINTERPRET_CAST_1:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_0]] to offset: [0], sizes: [2], strides: [1] : memref<*xf32> to memref<2xf32, strided<[1]>>
// CHECK:           %[[SUBVIEW_1:.*]] = memref.subview %[[ALLOC_0]][2] [2] [1] : memref<4xf32> to memref<2xf32, strided<[1], offset: 2>>
// CHECK:           memref.copy %[[REINTERPRET_CAST_1]], %[[SUBVIEW_1]] : memref<2xf32, strided<[1]>> to memref<2xf32, strided<[1], offset: 2>>
// CHECK:           %[[TO_TENSOR_0:.*]] = bufferization.to_tensor %[[ALLOC_0]] restrict writable : memref<4xf32> to tensor<4xf32>
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_1:.*]] = builtin.unrealized_conversion_cast %[[ARG1]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:           %[[REINTERPRET_CAST_2:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_1]] to offset: [6], sizes: [2], strides: [1] : memref<*xf32> to memref<2xf32, strided<[1], offset: 6>>
// CHECK:           %[[EXTRACT_SLICE_0:.*]] = tensor.extract_slice %[[TO_TENSOR_0]][0] [2] [1] : tensor<4xf32> to tensor<2xf32>
// CHECK:           bufferization.materialize_in_destination %[[EXTRACT_SLICE_0]] in writable %[[REINTERPRET_CAST_2]] : (tensor<2xf32>, memref<2xf32, strided<[1], offset: 6>>) -> ()
// CHECK:           %[[REINTERPRET_CAST_3:.*]] = memref.reinterpret_cast %[[UNREALIZED_CONVERSION_CAST_1]] to offset: [0], sizes: [2], strides: [1] : memref<*xf32> to memref<2xf32, strided<[1]>>
// CHECK:           %[[EXTRACT_SLICE_1:.*]] = tensor.extract_slice %[[TO_TENSOR_0]][2] [2] [1] : tensor<4xf32> to tensor<2xf32>
// CHECK:           bufferization.materialize_in_destination %[[EXTRACT_SLICE_1]] in writable %[[REINTERPRET_CAST_3]] : (tensor<2xf32>, memref<2xf32, strided<[1]>>) -> ()
// CHECK:           tt.return
// CHECK:         }
  tt.func @wrap_boundary_rank1_segmented_load_store(%src: !tt.ptr<f32>, %dst: !tt.ptr<f32>) {
    %src_addr = tta.make_addr %src to sizes: [4], strides: [1], offsets: [6], wrap_boundaries: [8], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
    %other = arith.constant 0.0 : f32
    %val = "tta.load"(%src_addr, %other) <{operandSegmentSizes = array<i32: 1, 0, 1>, static_mask_dims = array<i64>}> : (!tta.addr<f32, 1, 1>, f32) -> tensor<4xf32>
    %dst_addr = tta.make_addr %dst to sizes: [4], strides: [1], offsets: [6], wrap_boundaries: [8], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
    "tta.store"(%dst_addr, %val) <{static_mask_dims = array<i64>}> : (!tta.addr<f32, 1, 1>, tensor<4xf32>) -> ()
    tt.return
  }
}

// -----

module {
// CHECK-LABEL:   tt.func @wrap_boundary_load_store(
// CHECK-SAME:      %[[ARG0:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG1:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 3 : index
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 1 : index
// CHECK:           %[[CONSTANT_2:.*]] = arith.constant 0 : index
// CHECK:           %[[CONSTANT_3:.*]] = arith.constant 4 : index
// CHECK:           %[[CONSTANT_4:.*]] = arith.constant 2 : index
// CHECK:           %[[CONSTANT_5:.*]] = arith.constant 0.000000e+00 : f32
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:           %[[ALLOC_0:.*]] = memref.alloc() : memref<2x4xf32>
// CHECK:           linalg.fill ins(%[[CONSTANT_5]] : f32) outs(%[[ALLOC_0]] : memref<2x4xf32>)
// CHECK:           %[[CAST_0:.*]] = memref.cast %[[UNREALIZED_CONVERSION_CAST_0]] : memref<*xf32> to memref<?xf32>
// CHECK:           scf.for %[[VAL_0:.*]] = %[[CONSTANT_2]] to %[[CONSTANT_4]] step %[[CONSTANT_1]] {
// CHECK:             scf.for %[[VAL_1:.*]] = %[[CONSTANT_2]] to %[[CONSTANT_3]] step %[[CONSTANT_1]] {
// CHECK:               %[[MULI_0:.*]] = arith.muli %[[VAL_0]], %[[CONSTANT_3]] : index
// CHECK:               %[[ADDI_0:.*]] = arith.addi %[[VAL_1]], %[[CONSTANT_0]] : index
// CHECK:               %[[REMSI_0:.*]] = arith.remsi %[[ADDI_0]], %[[CONSTANT_3]] : index
// CHECK:               %[[CMPI_0:.*]] = arith.cmpi slt, %[[REMSI_0]], %[[CONSTANT_2]] : index
// CHECK:               %[[ADDI_1:.*]] = arith.addi %[[REMSI_0]], %[[CONSTANT_3]] : index
// CHECK:               %[[SELECT_0:.*]] = arith.select %[[CMPI_0]], %[[ADDI_1]], %[[REMSI_0]] : index
// CHECK:               %[[ADDI_2:.*]] = arith.addi %[[MULI_0]], %[[SELECT_0]] : index
// CHECK:               %[[LOAD_0:.*]] = memref.load %[[CAST_0]]{{\[}}%[[ADDI_2]]] : memref<?xf32>
// CHECK:               memref.store %[[LOAD_0]], %[[ALLOC_0]]{{\[}}%[[VAL_0]], %[[VAL_1]]] : memref<2x4xf32>
// CHECK:             }
// CHECK:           }
// CHECK:           %[[TO_TENSOR_0:.*]] = bufferization.to_tensor %[[ALLOC_0]] restrict writable : memref<2x4xf32> to tensor<2x4xf32>
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_1:.*]] = builtin.unrealized_conversion_cast %[[ARG1]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:           %[[CAST_1:.*]] = memref.cast %[[UNREALIZED_CONVERSION_CAST_1]] : memref<*xf32> to memref<?xf32>
// CHECK:           scf.for %[[VAL_2:.*]] = %[[CONSTANT_2]] to %[[CONSTANT_4]] step %[[CONSTANT_1]] {
// CHECK:             scf.for %[[VAL_3:.*]] = %[[CONSTANT_2]] to %[[CONSTANT_3]] step %[[CONSTANT_1]] {
// CHECK:               %[[MULI_1:.*]] = arith.muli %[[VAL_2]], %[[CONSTANT_3]] : index
// CHECK:               %[[ADDI_3:.*]] = arith.addi %[[VAL_3]], %[[CONSTANT_1]] : index
// CHECK:               %[[REMSI_1:.*]] = arith.remsi %[[ADDI_3]], %[[CONSTANT_3]] : index
// CHECK:               %[[CMPI_1:.*]] = arith.cmpi slt, %[[REMSI_1]], %[[CONSTANT_2]] : index
// CHECK:               %[[ADDI_4:.*]] = arith.addi %[[REMSI_1]], %[[CONSTANT_3]] : index
// CHECK:               %[[SELECT_1:.*]] = arith.select %[[CMPI_1]], %[[ADDI_4]], %[[REMSI_1]] : index
// CHECK:               %[[ADDI_5:.*]] = arith.addi %[[MULI_1]], %[[SELECT_1]] : index
// CHECK:               %[[EXTRACT_0:.*]] = tensor.extract %[[TO_TENSOR_0]]{{\[}}%[[VAL_2]], %[[VAL_3]]] : tensor<2x4xf32>
// CHECK:               memref.store %[[EXTRACT_0]], %[[CAST_1]]{{\[}}%[[ADDI_5]]] : memref<?xf32>
// CHECK:             }
// CHECK:           }
// CHECK:           tt.return
// CHECK:         }
  tt.func @wrap_boundary_load_store(%src: !tt.ptr<f32>, %dst: !tt.ptr<f32>) {
    %src_addr = tta.make_addr %src to sizes: [2, 4], strides: [4, 1], offsets: [0, 3], wrap_boundaries: [0, 4], layout: "strided" : <f32> to !tta.addr<f32, 2, 1>
    %other = arith.constant 0.0 : f32
    %val = "tta.load"(%src_addr, %other) <{operandSegmentSizes = array<i32: 1, 0, 1>, static_mask_dims = array<i64>}> : (!tta.addr<f32, 2, 1>, f32) -> tensor<2x4xf32>

    %dst_addr = tta.make_addr %dst to sizes: [2, 4], strides: [4, 1], offsets: [0, 1], wrap_boundaries: [0, 4], layout: "strided" : <f32> to !tta.addr<f32, 2, 1>
    "tta.store"(%dst_addr, %val) <{static_mask_dims = array<i64>}> : (!tta.addr<f32, 2, 1>, tensor<2x4xf32>) -> ()
    tt.return
  }
}

// -----

module {
// CHECK-LABEL:   tt.func @wrap_boundary_mixed_indirect_load_store(
// CHECK-SAME:      %[[ARG0:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG1:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant dense<[0, 1]> : tensor<2xindex>
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 3 : index
// CHECK:           %[[CONSTANT_2:.*]] = arith.constant 1 : index
// CHECK:           %[[CONSTANT_3:.*]] = arith.constant 0 : index
// CHECK:           %[[CONSTANT_4:.*]] = arith.constant 4 : index
// CHECK:           %[[CONSTANT_5:.*]] = arith.constant 2 : index
// CHECK:           %[[CONSTANT_6:.*]] = arith.constant 0.000000e+00 : f32
// CHECK:           %[[CONSTANT_7:.*]] = arith.constant dense<[true, false]> : tensor<2xi1>
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:           %[[ALLOC_0:.*]] = memref.alloc() : memref<2x4xf32>
// CHECK:           linalg.fill ins(%[[CONSTANT_6]] : f32) outs(%[[ALLOC_0]] : memref<2x4xf32>)
// CHECK:           %[[CAST_0:.*]] = memref.cast %[[UNREALIZED_CONVERSION_CAST_0]] : memref<*xf32> to memref<?xf32>
// CHECK:           scf.for %[[VAL_0:.*]] = %[[CONSTANT_3]] to %[[CONSTANT_5]] step %[[CONSTANT_2]] {
// CHECK:             scf.for %[[VAL_1:.*]] = %[[CONSTANT_3]] to %[[CONSTANT_4]] step %[[CONSTANT_2]] {
// CHECK:               %[[EXTRACT_0:.*]] = tensor.extract %[[CONSTANT_7]]{{\[}}%[[VAL_0]]] : tensor<2xi1>
// CHECK:               scf.if %[[EXTRACT_0]] {
// CHECK:                 %[[EXTRACT_1:.*]] = tensor.extract %[[CONSTANT_0]]{{\[}}%[[VAL_0]]] : tensor<2xindex>
// CHECK:                 %[[MULI_0:.*]] = arith.muli %[[EXTRACT_1]], %[[CONSTANT_4]] : index
// CHECK:                 %[[ADDI_0:.*]] = arith.addi %[[VAL_1]], %[[CONSTANT_1]] : index
// CHECK:                 %[[REMSI_0:.*]] = arith.remsi %[[ADDI_0]], %[[CONSTANT_4]] : index
// CHECK:                 %[[CMPI_0:.*]] = arith.cmpi slt, %[[REMSI_0]], %[[CONSTANT_3]] : index
// CHECK:                 %[[ADDI_1:.*]] = arith.addi %[[REMSI_0]], %[[CONSTANT_4]] : index
// CHECK:                 %[[SELECT_0:.*]] = arith.select %[[CMPI_0]], %[[ADDI_1]], %[[REMSI_0]] : index
// CHECK:                 %[[ADDI_2:.*]] = arith.addi %[[MULI_0]], %[[SELECT_0]] : index
// CHECK:                 %[[LOAD_0:.*]] = memref.load %[[CAST_0]]{{\[}}%[[ADDI_2]]] : memref<?xf32>
// CHECK:                 memref.store %[[LOAD_0]], %[[ALLOC_0]]{{\[}}%[[VAL_0]], %[[VAL_1]]] : memref<2x4xf32>
// CHECK:               }
// CHECK:             }
// CHECK:           }
// CHECK:           %[[TO_TENSOR_0:.*]] = bufferization.to_tensor %[[ALLOC_0]] restrict writable : memref<2x4xf32> to tensor<2x4xf32>
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_1:.*]] = builtin.unrealized_conversion_cast %[[ARG1]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:           %[[CAST_1:.*]] = memref.cast %[[UNREALIZED_CONVERSION_CAST_1]] : memref<*xf32> to memref<?xf32>
// CHECK:           scf.for %[[VAL_2:.*]] = %[[CONSTANT_3]] to %[[CONSTANT_5]] step %[[CONSTANT_2]] {
// CHECK:             scf.for %[[VAL_3:.*]] = %[[CONSTANT_3]] to %[[CONSTANT_4]] step %[[CONSTANT_2]] {
// CHECK:               %[[EXTRACT_2:.*]] = tensor.extract %[[CONSTANT_7]]{{\[}}%[[VAL_2]]] : tensor<2xi1>
// CHECK:               scf.if %[[EXTRACT_2]] {
// CHECK:                 %[[EXTRACT_3:.*]] = tensor.extract %[[CONSTANT_0]]{{\[}}%[[VAL_2]]] : tensor<2xindex>
// CHECK:                 %[[MULI_1:.*]] = arith.muli %[[EXTRACT_3]], %[[CONSTANT_4]] : index
// CHECK:                 %[[ADDI_3:.*]] = arith.addi %[[VAL_3]], %[[CONSTANT_2]] : index
// CHECK:                 %[[REMSI_1:.*]] = arith.remsi %[[ADDI_3]], %[[CONSTANT_4]] : index
// CHECK:                 %[[CMPI_1:.*]] = arith.cmpi slt, %[[REMSI_1]], %[[CONSTANT_3]] : index
// CHECK:                 %[[ADDI_4:.*]] = arith.addi %[[REMSI_1]], %[[CONSTANT_4]] : index
// CHECK:                 %[[SELECT_1:.*]] = arith.select %[[CMPI_1]], %[[ADDI_4]], %[[REMSI_1]] : index
// CHECK:                 %[[ADDI_5:.*]] = arith.addi %[[MULI_1]], %[[SELECT_1]] : index
// CHECK:                 %[[EXTRACT_4:.*]] = tensor.extract %[[TO_TENSOR_0]]{{\[}}%[[VAL_2]], %[[VAL_3]]] : tensor<2x4xf32>
// CHECK:                 memref.store %[[EXTRACT_4]], %[[CAST_1]]{{\[}}%[[ADDI_5]]] : memref<?xf32>
// CHECK:               }
// CHECK:             }
// CHECK:           }
// CHECK:           tt.return
// CHECK:         }
  tt.func @wrap_boundary_mixed_indirect_load_store(%src: !tt.ptr<f32>, %dst: !tt.ptr<f32>) {
    %idx = arith.constant dense<[0, 1]> : tensor<2xi32>
    %mask = arith.constant dense<[true, false]> : tensor<2xi1>

    %src_addr = tta.make_addr %src to sizes: [2, 4], strides: [4, 1], offsets: [0, 3], wrap_boundaries: [0, 4], layout: "strided" : <f32> to !tta.addr<f32, 2, 1>
    %src_idx = "tta.indirect_reindex"(%src_addr, %idx, %mask) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 2, 1>, tensor<2xi32>, tensor<2xi1>) -> !tta.addr<f32, 2, 1>
    %other = arith.constant 0.0 : f32
    %val = "tta.load"(%src_idx, %other) <{operandSegmentSizes = array<i32: 1, 0, 1>, static_mask_dims = array<i64>}> : (!tta.addr<f32, 2, 1>, f32) -> tensor<2x4xf32>

    %dst_addr = tta.make_addr %dst to sizes: [2, 4], strides: [4, 1], offsets: [0, 1], wrap_boundaries: [0, 4], layout: "strided" : <f32> to !tta.addr<f32, 2, 1>
    %dst_idx = "tta.indirect_reindex"(%dst_addr, %idx, %mask) <{indirect_dim = 0 : i32}> : (!tta.addr<f32, 2, 1>, tensor<2xi32>, tensor<2xi1>) -> !tta.addr<f32, 2, 1>
    "tta.store"(%dst_idx, %val) <{static_mask_dims = array<i64>}> : (!tta.addr<f32, 2, 1>, tensor<2x4xf32>) -> ()
    tt.return
  }
}

// -----

module {
// CHECK-LABEL:   tt.func @wrap_boundary_negative_offset_load_store(
// CHECK-SAME:      %[[ARG0:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG1:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant -3 : index
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant -1 : index
// CHECK:           %[[CONSTANT_2:.*]] = arith.constant 1 : index
// CHECK:           %[[CONSTANT_3:.*]] = arith.constant 0 : index
// CHECK:           %[[CONSTANT_4:.*]] = arith.constant 4 : index
// CHECK:           %[[CONSTANT_5:.*]] = arith.constant 2 : index
// CHECK:           %[[CONSTANT_6:.*]] = arith.constant 0.000000e+00 : f32
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:           %[[ALLOC_0:.*]] = memref.alloc() : memref<2x4xf32>
// CHECK:           linalg.fill ins(%[[CONSTANT_6]] : f32) outs(%[[ALLOC_0]] : memref<2x4xf32>)
// CHECK:           %[[CAST_0:.*]] = memref.cast %[[UNREALIZED_CONVERSION_CAST_0]] : memref<*xf32> to memref<?xf32>
// CHECK:           scf.for %[[VAL_0:.*]] = %[[CONSTANT_3]] to %[[CONSTANT_5]] step %[[CONSTANT_2]] {
// CHECK:             scf.for %[[VAL_1:.*]] = %[[CONSTANT_3]] to %[[CONSTANT_4]] step %[[CONSTANT_2]] {
// CHECK:               %[[MULI_0:.*]] = arith.muli %[[VAL_0]], %[[CONSTANT_4]] : index
// CHECK:               %[[ADDI_0:.*]] = arith.addi %[[VAL_1]], %[[CONSTANT_1]] : index
// CHECK:               %[[REMSI_0:.*]] = arith.remsi %[[ADDI_0]], %[[CONSTANT_4]] : index
// CHECK:               %[[CMPI_0:.*]] = arith.cmpi slt, %[[REMSI_0]], %[[CONSTANT_3]] : index
// CHECK:               %[[ADDI_1:.*]] = arith.addi %[[REMSI_0]], %[[CONSTANT_4]] : index
// CHECK:               %[[SELECT_0:.*]] = arith.select %[[CMPI_0]], %[[ADDI_1]], %[[REMSI_0]] : index
// CHECK:               %[[ADDI_2:.*]] = arith.addi %[[MULI_0]], %[[SELECT_0]] : index
// CHECK:               %[[LOAD_0:.*]] = memref.load %[[CAST_0]]{{\[}}%[[ADDI_2]]] : memref<?xf32>
// CHECK:               memref.store %[[LOAD_0]], %[[ALLOC_0]]{{\[}}%[[VAL_0]], %[[VAL_1]]] : memref<2x4xf32>
// CHECK:             }
// CHECK:           }
// CHECK:           %[[TO_TENSOR_0:.*]] = bufferization.to_tensor %[[ALLOC_0]] restrict writable : memref<2x4xf32> to tensor<2x4xf32>
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_1:.*]] = builtin.unrealized_conversion_cast %[[ARG1]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:           %[[CAST_1:.*]] = memref.cast %[[UNREALIZED_CONVERSION_CAST_1]] : memref<*xf32> to memref<?xf32>
// CHECK:           scf.for %[[VAL_2:.*]] = %[[CONSTANT_3]] to %[[CONSTANT_5]] step %[[CONSTANT_2]] {
// CHECK:             scf.for %[[VAL_3:.*]] = %[[CONSTANT_3]] to %[[CONSTANT_4]] step %[[CONSTANT_2]] {
// CHECK:               %[[MULI_1:.*]] = arith.muli %[[VAL_2]], %[[CONSTANT_4]] : index
// CHECK:               %[[ADDI_3:.*]] = arith.addi %[[VAL_3]], %[[CONSTANT_0]] : index
// CHECK:               %[[REMSI_1:.*]] = arith.remsi %[[ADDI_3]], %[[CONSTANT_4]] : index
// CHECK:               %[[CMPI_1:.*]] = arith.cmpi slt, %[[REMSI_1]], %[[CONSTANT_3]] : index
// CHECK:               %[[ADDI_4:.*]] = arith.addi %[[REMSI_1]], %[[CONSTANT_4]] : index
// CHECK:               %[[SELECT_1:.*]] = arith.select %[[CMPI_1]], %[[ADDI_4]], %[[REMSI_1]] : index
// CHECK:               %[[ADDI_5:.*]] = arith.addi %[[MULI_1]], %[[SELECT_1]] : index
// CHECK:               %[[EXTRACT_0:.*]] = tensor.extract %[[TO_TENSOR_0]]{{\[}}%[[VAL_2]], %[[VAL_3]]] : tensor<2x4xf32>
// CHECK:               memref.store %[[EXTRACT_0]], %[[CAST_1]]{{\[}}%[[ADDI_5]]] : memref<?xf32>
// CHECK:             }
// CHECK:           }
// CHECK:           tt.return
// CHECK:         }
  tt.func @wrap_boundary_negative_offset_load_store(%src: !tt.ptr<f32>, %dst: !tt.ptr<f32>) {
    %src_addr = tta.make_addr %src to sizes: [2, 4], strides: [4, 1], offsets: [0, -1], wrap_boundaries: [0, 4], layout: "strided" : <f32> to !tta.addr<f32, 2, 1>
    %other = arith.constant 0.0 : f32
    %val = "tta.load"(%src_addr, %other) <{operandSegmentSizes = array<i32: 1, 0, 1>, static_mask_dims = array<i64>}> : (!tta.addr<f32, 2, 1>, f32) -> tensor<2x4xf32>

    %dst_addr = tta.make_addr %dst to sizes: [2, 4], strides: [4, 1], offsets: [0, -3], wrap_boundaries: [0, 4], layout: "strided" : <f32> to !tta.addr<f32, 2, 1>
    "tta.store"(%dst_addr, %val) <{static_mask_dims = array<i64>}> : (!tta.addr<f32, 2, 1>, tensor<2x4xf32>) -> ()
    tt.return
  }
}

// -----

module {
// CHECK-LABEL:   tt.func @wrap_boundary_dynamic_guard(
// CHECK-SAME:      %[[ARG0:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG1:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG2:[-0-9A-Za-z$._]+]]: index) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 2 : index
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 1 : index
// CHECK:           %[[CONSTANT_2:.*]] = arith.constant 0 : index
// CHECK:           %[[CONSTANT_3:.*]] = arith.constant 4 : index
// CHECK:           %[[CONSTANT_4:.*]] = arith.constant 0.000000e+00 : f32
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:           %[[ALLOC_0:.*]] = memref.alloc() : memref<4xf32>
// CHECK:           linalg.fill ins(%[[CONSTANT_4]] : f32) outs(%[[ALLOC_0]] : memref<4xf32>)
// CHECK:           %[[CAST_0:.*]] = memref.cast %[[UNREALIZED_CONVERSION_CAST_0]] : memref<*xf32> to memref<?xf32>
// CHECK:           scf.for %[[VAL_0:.*]] = %[[CONSTANT_2]] to %[[CONSTANT_3]] step %[[CONSTANT_1]] {
// CHECK:             %[[ADDI_0:.*]] = arith.addi %[[VAL_0]], %[[CONSTANT_1]] : index
// CHECK:             %[[CMPI_0:.*]] = arith.cmpi sgt, %[[ARG2]], %[[CONSTANT_2]] : index
// CHECK:             cf.assert %[[CMPI_0]], "tta-to-memref: wrap boundary must be > 0"
// CHECK:             %[[REMSI_0:.*]] = arith.remsi %[[ADDI_0]], %[[ARG2]] : index
// CHECK:             %[[CMPI_1:.*]] = arith.cmpi slt, %[[REMSI_0]], %[[CONSTANT_2]] : index
// CHECK:             %[[ADDI_1:.*]] = arith.addi %[[REMSI_0]], %[[ARG2]] : index
// CHECK:             %[[SELECT_0:.*]] = arith.select %[[CMPI_1]], %[[ADDI_1]], %[[REMSI_0]] : index
// CHECK:             %[[LOAD_0:.*]] = memref.load %[[CAST_0]]{{\[}}%[[SELECT_0]]] : memref<?xf32>
// CHECK:             memref.store %[[LOAD_0]], %[[ALLOC_0]]{{\[}}%[[VAL_0]]] : memref<4xf32>
// CHECK:           }
// CHECK:           %[[TO_TENSOR_0:.*]] = bufferization.to_tensor %[[ALLOC_0]] restrict writable : memref<4xf32> to tensor<4xf32>
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_1:.*]] = builtin.unrealized_conversion_cast %[[ARG1]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:           %[[CAST_1:.*]] = memref.cast %[[UNREALIZED_CONVERSION_CAST_1]] : memref<*xf32> to memref<?xf32>
// CHECK:           scf.for %[[VAL_1:.*]] = %[[CONSTANT_2]] to %[[CONSTANT_3]] step %[[CONSTANT_1]] {
// CHECK:             %[[ADDI_2:.*]] = arith.addi %[[VAL_1]], %[[CONSTANT_0]] : index
// CHECK:             %[[CMPI_2:.*]] = arith.cmpi sgt, %[[ARG2]], %[[CONSTANT_2]] : index
// CHECK:             cf.assert %[[CMPI_2]], "tta-to-memref: wrap boundary must be > 0"
// CHECK:             %[[REMSI_1:.*]] = arith.remsi %[[ADDI_2]], %[[ARG2]] : index
// CHECK:             %[[CMPI_3:.*]] = arith.cmpi slt, %[[REMSI_1]], %[[CONSTANT_2]] : index
// CHECK:             %[[ADDI_3:.*]] = arith.addi %[[REMSI_1]], %[[ARG2]] : index
// CHECK:             %[[SELECT_1:.*]] = arith.select %[[CMPI_3]], %[[ADDI_3]], %[[REMSI_1]] : index
// CHECK:             %[[EXTRACT_0:.*]] = tensor.extract %[[TO_TENSOR_0]]{{\[}}%[[VAL_1]]] : tensor<4xf32>
// CHECK:             memref.store %[[EXTRACT_0]], %[[CAST_1]]{{\[}}%[[SELECT_1]]] : memref<?xf32>
// CHECK:           }
// CHECK:           tt.return
// CHECK:         }
  tt.func @wrap_boundary_dynamic_guard(%src: !tt.ptr<f32>, %dst: !tt.ptr<f32>, %boundary: index) {
    %src_addr = tta.make_addr %src to sizes: [4], strides: [1], offsets: [1], wrap_boundaries: [%boundary], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
    %other = arith.constant 0.0 : f32
    %val = "tta.load"(%src_addr, %other) <{operandSegmentSizes = array<i32: 1, 0, 1>, static_mask_dims = array<i64>}> : (!tta.addr<f32, 1, 1>, f32) -> tensor<4xf32>
    %dst_addr = tta.make_addr %dst to sizes: [4], strides: [1], offsets: [2], wrap_boundaries: [%boundary], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
    "tta.store"(%dst_addr, %val) <{static_mask_dims = array<i64>}> : (!tta.addr<f32, 1, 1>, tensor<4xf32>) -> ()
    tt.return
  }
}

// -----

module {
// CHECK-LABEL:   tt.func @atomic_scalar_basic(
// CHECK-SAME:      %[[ARG0:[-0-9A-Za-z$._]+]]: !tt.ptr<i32>,
// CHECK-SAME:      %[[ARG1:[-0-9A-Za-z$._]+]]: i32,
// CHECK-SAME:      %[[ARG2:[-0-9A-Za-z$._]+]]: i32,
// CHECK-SAME:      %[[ARG3:[-0-9A-Za-z$._]+]]: i1) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 0 : i32
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<i32> to memref<*xi32>
// CHECK:           %[[CAST_0:.*]] = memref.cast %[[UNREALIZED_CONVERSION_CAST_0]] : memref<*xi32> to memref<?xi32>
// CHECK:           %[[INDEX_CAST_0:.*]] = arith.index_cast %[[ARG1]] : i32 to index
// CHECK:           %[[IF_0:.*]] = scf.if %[[ARG3]] -> (i32) {
// CHECK:             %[[ATOMIC_RMW_0:.*]] = memref.atomic_rmw addi %[[ARG2]], %[[CAST_0]]{{\[}}%[[INDEX_CAST_0]]] : (i32, memref<?xi32>) -> i32
// CHECK:             scf.yield %[[ATOMIC_RMW_0]] : i32
// CHECK:           } else {
// CHECK:             scf.yield %[[CONSTANT_0]] : i32
// CHECK:           }
// CHECK:           %[[ATOMIC_RMW_1:.*]] = memref.atomic_rmw assign %[[IF_0]], %[[CAST_0]]{{\[}}%[[INDEX_CAST_0]]] : (i32, memref<?xi32>) -> i32
// CHECK:           tt.return
// CHECK:         }
  tt.func @atomic_scalar_basic(%ptr: !tt.ptr<i32>, %off: i32, %val: i32, %mask: i1) {
    %ptr_i = tta.make_addr %ptr to sizes: [1], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <i32> to !tta.addr<i32, 1, 1>
    %r0 = "tta.atomic"(%ptr_i, %off, %val, %mask) <{kind = "add"}> : (!tta.addr<i32, 1, 1>, i32, i32, i1) -> i32
    %r1 = "tta.atomic"(%ptr_i, %off, %r0) <{kind = "xchg"}> : (!tta.addr<i32, 1, 1>, i32, i32) -> i32
    %r2 = arith.addi %r0, %r1 : i32
    %r3 = arith.addi %r2, %val : i32
    tt.return
  }
}

// -----

module {
// CHECK-LABEL:   tt.func @atomic_scalar_wrap_boundary(
// CHECK-SAME:      %[[ARG0:[-0-9A-Za-z$._]+]]: !tt.ptr<i32>,
// CHECK-SAME:      %[[ARG1:[-0-9A-Za-z$._]+]]: i32,
// CHECK-SAME:      %[[ARG2:[-0-9A-Za-z$._]+]]: i32) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 0 : index
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 8 : index
// CHECK:           %[[CONSTANT_2:.*]] = arith.constant 3 : index
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<i32> to memref<*xi32>
// CHECK:           %[[CAST_0:.*]] = memref.cast %[[UNREALIZED_CONVERSION_CAST_0]] : memref<*xi32> to memref<?xi32>
// CHECK:           %[[INDEX_CAST_0:.*]] = arith.index_cast %[[ARG1]] : i32 to index
// CHECK:           %[[ADDI_0:.*]] = arith.addi %[[INDEX_CAST_0]], %[[CONSTANT_2]] : index
// CHECK:           %[[REMSI_0:.*]] = arith.remsi %[[ADDI_0]], %[[CONSTANT_1]] : index
// CHECK:           %[[CMPI_0:.*]] = arith.cmpi slt, %[[REMSI_0]], %[[CONSTANT_0]] : index
// CHECK:           %[[ADDI_1:.*]] = arith.addi %[[REMSI_0]], %[[CONSTANT_1]] : index
// CHECK:           %[[SELECT_0:.*]] = arith.select %[[CMPI_0]], %[[ADDI_1]], %[[REMSI_0]] : index
// CHECK:           %[[ATOMIC_RMW_0:.*]] = memref.atomic_rmw addi %[[ARG2]], %[[CAST_0]]{{\[}}%[[SELECT_0]]] : (i32, memref<?xi32>) -> i32
// CHECK:           tt.return
// CHECK:         }
  tt.func @atomic_scalar_wrap_boundary(%ptr: !tt.ptr<i32>, %off: i32, %val: i32) {
    %ptr_i = tta.make_addr %ptr to sizes: [16], strides: [1], offsets: [3], wrap_boundaries: [8], layout: "strided" : <i32> to !tta.addr<i32, 1, 1>
    %r = "tta.atomic"(%ptr_i, %off, %val) <{kind = "add"}> : (!tta.addr<i32, 1, 1>, i32, i32) -> i32
    %u = arith.addi %r, %val : i32
    tt.return
  }
}

// -----

module {
// CHECK-LABEL:   tt.func @atomic_scalar_wrap_negative_boundary(
// CHECK-SAME:      %[[ARG0:[-0-9A-Za-z$._]+]]: !tt.ptr<i32>,
// CHECK-SAME:      %[[ARG1:[-0-9A-Za-z$._]+]]: i32,
// CHECK-SAME:      %[[ARG2:[-0-9A-Za-z$._]+]]: i32) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 0 : index
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 8 : index
// CHECK:           %[[CONSTANT_2:.*]] = arith.constant -5 : index
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<i32> to memref<*xi32>
// CHECK:           %[[CAST_0:.*]] = memref.cast %[[UNREALIZED_CONVERSION_CAST_0]] : memref<*xi32> to memref<?xi32>
// CHECK:           %[[INDEX_CAST_0:.*]] = arith.index_cast %[[ARG1]] : i32 to index
// CHECK:           %[[ADDI_0:.*]] = arith.addi %[[INDEX_CAST_0]], %[[CONSTANT_2]] : index
// CHECK:           %[[REMSI_0:.*]] = arith.remsi %[[ADDI_0]], %[[CONSTANT_1]] : index
// CHECK:           %[[CMPI_0:.*]] = arith.cmpi slt, %[[REMSI_0]], %[[CONSTANT_0]] : index
// CHECK:           %[[ADDI_1:.*]] = arith.addi %[[REMSI_0]], %[[CONSTANT_1]] : index
// CHECK:           %[[SELECT_0:.*]] = arith.select %[[CMPI_0]], %[[ADDI_1]], %[[REMSI_0]] : index
// CHECK:           %[[ATOMIC_RMW_0:.*]] = memref.atomic_rmw addi %[[ARG2]], %[[CAST_0]]{{\[}}%[[SELECT_0]]] : (i32, memref<?xi32>) -> i32
// CHECK:           tt.return
// CHECK:         }
  tt.func @atomic_scalar_wrap_negative_boundary(%ptr: !tt.ptr<i32>, %off: i32, %val: i32) {
    %ptr_i = tta.make_addr %ptr to sizes: [16], strides: [1], offsets: [-5], wrap_boundaries: [8], layout: "strided" : <i32> to !tta.addr<i32, 1, 1>
    %r = "tta.atomic"(%ptr_i, %off, %val) <{kind = "add"}> : (!tta.addr<i32, 1, 1>, i32, i32) -> i32
    %u = arith.addi %r, %val : i32
    tt.return
  }
}

// -----

module {
// CHECK-LABEL:   tt.func @atomic_scalar_wrap_dynamic_boundary(
// CHECK-SAME:      %[[ARG0:[-0-9A-Za-z$._]+]]: !tt.ptr<i32>,
// CHECK-SAME:      %[[ARG1:[-0-9A-Za-z$._]+]]: i32,
// CHECK-SAME:      %[[ARG2:[-0-9A-Za-z$._]+]]: i32,
// CHECK-SAME:      %[[ARG3:[-0-9A-Za-z$._]+]]: index) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 0 : index
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 2 : index
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<i32> to memref<*xi32>
// CHECK:           %[[CAST_0:.*]] = memref.cast %[[UNREALIZED_CONVERSION_CAST_0]] : memref<*xi32> to memref<?xi32>
// CHECK:           %[[INDEX_CAST_0:.*]] = arith.index_cast %[[ARG1]] : i32 to index
// CHECK:           %[[ADDI_0:.*]] = arith.addi %[[INDEX_CAST_0]], %[[CONSTANT_1]] : index
// CHECK:           %[[CMPI_0:.*]] = arith.cmpi sgt, %[[ARG3]], %[[CONSTANT_0]] : index
// CHECK:           cf.assert %[[CMPI_0]], "tta-to-memref: wrap boundary must be > 0"
// CHECK:           %[[REMSI_0:.*]] = arith.remsi %[[ADDI_0]], %[[ARG3]] : index
// CHECK:           %[[CMPI_1:.*]] = arith.cmpi slt, %[[REMSI_0]], %[[CONSTANT_0]] : index
// CHECK:           %[[ADDI_1:.*]] = arith.addi %[[REMSI_0]], %[[ARG3]] : index
// CHECK:           %[[SELECT_0:.*]] = arith.select %[[CMPI_1]], %[[ADDI_1]], %[[REMSI_0]] : index
// CHECK:           %[[ATOMIC_RMW_0:.*]] = memref.atomic_rmw addi %[[ARG2]], %[[CAST_0]]{{\[}}%[[SELECT_0]]] : (i32, memref<?xi32>) -> i32
// CHECK:           tt.return
// CHECK:         }
  tt.func @atomic_scalar_wrap_dynamic_boundary(%ptr: !tt.ptr<i32>, %off: i32, %val: i32, %boundary: index) {
    %ptr_i = tta.make_addr %ptr to sizes: [16], strides: [1], offsets: [2], wrap_boundaries: [%boundary], layout: "strided" : <i32> to !tta.addr<i32, 1, 1>
    %r = "tta.atomic"(%ptr_i, %off, %val) <{kind = "add"}> : (!tta.addr<i32, 1, 1>, i32, i32) -> i32
    %u = arith.addi %r, %val : i32
    tt.return
  }
}

// -----

module {
// CHECK-LABEL:   tt.func @atomic_float_add(
// CHECK-SAME:      %[[ARG0:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG1:[-0-9A-Za-z$._]+]]: i32,
// CHECK-SAME:      %[[ARG2:[-0-9A-Za-z$._]+]]: f32) {
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:           %[[CAST_0:.*]] = memref.cast %[[UNREALIZED_CONVERSION_CAST_0]] : memref<*xf32> to memref<?xf32>
// CHECK:           %[[INDEX_CAST_0:.*]] = arith.index_cast %[[ARG1]] : i32 to index
// CHECK:           %[[ATOMIC_RMW_0:.*]] = memref.atomic_rmw addf %[[ARG2]], %[[CAST_0]]{{\[}}%[[INDEX_CAST_0]]] : (f32, memref<?xf32>) -> f32
// CHECK:           tt.return
// CHECK:         }
  tt.func @atomic_float_add(%ptr: !tt.ptr<f32>, %off: i32, %val: f32) {
    %ptr_i = tta.make_addr %ptr to sizes: [1], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
    %r = "tta.atomic"(%ptr_i, %off, %val) <{kind = "fadd"}> : (!tta.addr<f32, 1, 1>, i32, f32) -> f32
    %u = arith.addf %r, %val : f32
    tt.return
  }
}

// -----

module {
// CHECK-LABEL:   tt.func @atomic_cas_scalar_wrap_boundary(
// CHECK-SAME:      %[[ARG0:[-0-9A-Za-z$._]+]]: !tt.ptr<i32>,
// CHECK-SAME:      %[[ARG1:[-0-9A-Za-z$._]+]]: i32,
// CHECK-SAME:      %[[ARG2:[-0-9A-Za-z$._]+]]: i32,
// CHECK-SAME:      %[[ARG3:[-0-9A-Za-z$._]+]]: i32) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 0 : index
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 16 : index
// CHECK:           %[[CONSTANT_2:.*]] = arith.constant 5 : index
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<i32> to memref<*xi32>
// CHECK:           %[[CAST_0:.*]] = memref.cast %[[UNREALIZED_CONVERSION_CAST_0]] : memref<*xi32> to memref<?xi32>
// CHECK:           %[[INDEX_CAST_0:.*]] = arith.index_cast %[[ARG1]] : i32 to index
// CHECK:           %[[ADDI_0:.*]] = arith.addi %[[INDEX_CAST_0]], %[[CONSTANT_2]] : index
// CHECK:           %[[REMSI_0:.*]] = arith.remsi %[[ADDI_0]], %[[CONSTANT_1]] : index
// CHECK:           %[[CMPI_0:.*]] = arith.cmpi slt, %[[REMSI_0]], %[[CONSTANT_0]] : index
// CHECK:           %[[ADDI_1:.*]] = arith.addi %[[REMSI_0]], %[[CONSTANT_1]] : index
// CHECK:           %[[SELECT_0:.*]] = arith.select %[[CMPI_0]], %[[ADDI_1]], %[[REMSI_0]] : index
// CHECK:           %[[GENERIC_ATOMIC_RMW_0:.*]] = memref.generic_atomic_rmw %[[CAST_0]]{{\[}}%[[SELECT_0]]] : memref<?xi32> {
// CHECK:           ^bb0(%[[VAL_0:.*]]: i32):
// CHECK:             %[[CMPI_1:.*]] = arith.cmpi eq, %[[VAL_0]], %[[ARG2]] : i32
// CHECK:             %[[SELECT_1:.*]] = arith.select %[[CMPI_1]], %[[ARG3]], %[[VAL_0]] : i32
// CHECK:             memref.atomic_yield %[[SELECT_1]] : i32
// CHECK:           }
// CHECK:           tt.return
// CHECK:         }
  tt.func @atomic_cas_scalar_wrap_boundary(%ptr: !tt.ptr<i32>, %off: i32, %cmp: i32, %val: i32) {
    %ptr_i = tta.make_addr %ptr to sizes: [32], strides: [1], offsets: [5], wrap_boundaries: [16], layout: "strided" : <i32> to !tta.addr<i32, 1, 1>
    %r = "tta.atomic_cas"(%ptr_i, %off, %cmp, %val) : (!tta.addr<i32, 1, 1>, i32, i32, i32) -> i32
    %u = arith.addi %r, %val : i32
    tt.return
  }
}

// -----

module {
// CHECK-LABEL:   tt.func @atomic_cas_scalar_wrap_negative_boundary(
// CHECK-SAME:      %[[ARG0:[-0-9A-Za-z$._]+]]: !tt.ptr<i32>,
// CHECK-SAME:      %[[ARG1:[-0-9A-Za-z$._]+]]: i32,
// CHECK-SAME:      %[[ARG2:[-0-9A-Za-z$._]+]]: i32,
// CHECK-SAME:      %[[ARG3:[-0-9A-Za-z$._]+]]: i32) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 0 : index
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 16 : index
// CHECK:           %[[CONSTANT_2:.*]] = arith.constant -7 : index
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<i32> to memref<*xi32>
// CHECK:           %[[CAST_0:.*]] = memref.cast %[[UNREALIZED_CONVERSION_CAST_0]] : memref<*xi32> to memref<?xi32>
// CHECK:           %[[INDEX_CAST_0:.*]] = arith.index_cast %[[ARG1]] : i32 to index
// CHECK:           %[[ADDI_0:.*]] = arith.addi %[[INDEX_CAST_0]], %[[CONSTANT_2]] : index
// CHECK:           %[[REMSI_0:.*]] = arith.remsi %[[ADDI_0]], %[[CONSTANT_1]] : index
// CHECK:           %[[CMPI_0:.*]] = arith.cmpi slt, %[[REMSI_0]], %[[CONSTANT_0]] : index
// CHECK:           %[[ADDI_1:.*]] = arith.addi %[[REMSI_0]], %[[CONSTANT_1]] : index
// CHECK:           %[[SELECT_0:.*]] = arith.select %[[CMPI_0]], %[[ADDI_1]], %[[REMSI_0]] : index
// CHECK:           %[[GENERIC_ATOMIC_RMW_0:.*]] = memref.generic_atomic_rmw %[[CAST_0]]{{\[}}%[[SELECT_0]]] : memref<?xi32> {
// CHECK:           ^bb0(%[[VAL_0:.*]]: i32):
// CHECK:             %[[CMPI_1:.*]] = arith.cmpi eq, %[[VAL_0]], %[[ARG2]] : i32
// CHECK:             %[[SELECT_1:.*]] = arith.select %[[CMPI_1]], %[[ARG3]], %[[VAL_0]] : i32
// CHECK:             memref.atomic_yield %[[SELECT_1]] : i32
// CHECK:           }
// CHECK:           tt.return
// CHECK:         }
  tt.func @atomic_cas_scalar_wrap_negative_boundary(%ptr: !tt.ptr<i32>, %off: i32, %cmp: i32, %val: i32) {
    %ptr_i = tta.make_addr %ptr to sizes: [32], strides: [1], offsets: [-7], wrap_boundaries: [16], layout: "strided" : <i32> to !tta.addr<i32, 1, 1>
    %r = "tta.atomic_cas"(%ptr_i, %off, %cmp, %val) : (!tta.addr<i32, 1, 1>, i32, i32, i32) -> i32
    %u = arith.addi %r, %val : i32
    tt.return
  }
}

// -----

module {
// CHECK-LABEL:   tt.func @atomic_cas_scalar_wrap_dynamic_boundary(
// CHECK-SAME:      %[[ARG0:[-0-9A-Za-z$._]+]]: !tt.ptr<i32>,
// CHECK-SAME:      %[[ARG1:[-0-9A-Za-z$._]+]]: i32,
// CHECK-SAME:      %[[ARG2:[-0-9A-Za-z$._]+]]: i32,
// CHECK-SAME:      %[[ARG3:[-0-9A-Za-z$._]+]]: i32,
// CHECK-SAME:      %[[ARG4:[-0-9A-Za-z$._]+]]: index) {
// CHECK:           %[[CONSTANT_0:.*]] = arith.constant 0 : index
// CHECK:           %[[CONSTANT_1:.*]] = arith.constant 4 : index
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<i32> to memref<*xi32>
// CHECK:           %[[CAST_0:.*]] = memref.cast %[[UNREALIZED_CONVERSION_CAST_0]] : memref<*xi32> to memref<?xi32>
// CHECK:           %[[INDEX_CAST_0:.*]] = arith.index_cast %[[ARG1]] : i32 to index
// CHECK:           %[[ADDI_0:.*]] = arith.addi %[[INDEX_CAST_0]], %[[CONSTANT_1]] : index
// CHECK:           %[[CMPI_0:.*]] = arith.cmpi sgt, %[[ARG4]], %[[CONSTANT_0]] : index
// CHECK:           cf.assert %[[CMPI_0]], "tta-to-memref: wrap boundary must be > 0"
// CHECK:           %[[REMSI_0:.*]] = arith.remsi %[[ADDI_0]], %[[ARG4]] : index
// CHECK:           %[[CMPI_1:.*]] = arith.cmpi slt, %[[REMSI_0]], %[[CONSTANT_0]] : index
// CHECK:           %[[ADDI_1:.*]] = arith.addi %[[REMSI_0]], %[[ARG4]] : index
// CHECK:           %[[SELECT_0:.*]] = arith.select %[[CMPI_1]], %[[ADDI_1]], %[[REMSI_0]] : index
// CHECK:           %[[GENERIC_ATOMIC_RMW_0:.*]] = memref.generic_atomic_rmw %[[CAST_0]]{{\[}}%[[SELECT_0]]] : memref<?xi32> {
// CHECK:           ^bb0(%[[VAL_0:.*]]: i32):
// CHECK:             %[[CMPI_2:.*]] = arith.cmpi eq, %[[VAL_0]], %[[ARG2]] : i32
// CHECK:             %[[SELECT_1:.*]] = arith.select %[[CMPI_2]], %[[ARG3]], %[[VAL_0]] : i32
// CHECK:             memref.atomic_yield %[[SELECT_1]] : i32
// CHECK:           }
// CHECK:           tt.return
// CHECK:         }
  tt.func @atomic_cas_scalar_wrap_dynamic_boundary(%ptr: !tt.ptr<i32>, %off: i32, %cmp: i32, %val: i32, %boundary: index) {
    %ptr_i = tta.make_addr %ptr to sizes: [32], strides: [1], offsets: [4], wrap_boundaries: [%boundary], layout: "strided" : <i32> to !tta.addr<i32, 1, 1>
    %r = "tta.atomic_cas"(%ptr_i, %off, %cmp, %val) : (!tta.addr<i32, 1, 1>, i32, i32, i32) -> i32
    %u = arith.addi %r, %val : i32
    tt.return
  }
}

// -----

module {
// CHECK-LABEL:   tt.func @atomic_cas_scalar(
// CHECK-SAME:      %[[ARG0:[-0-9A-Za-z$._]+]]: !tt.ptr<i32>,
// CHECK-SAME:      %[[ARG1:[-0-9A-Za-z$._]+]]: i32,
// CHECK-SAME:      %[[ARG2:[-0-9A-Za-z$._]+]]: i32,
// CHECK-SAME:      %[[ARG3:[-0-9A-Za-z$._]+]]: i32) {
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<i32> to memref<*xi32>
// CHECK:           %[[CAST_0:.*]] = memref.cast %[[UNREALIZED_CONVERSION_CAST_0]] : memref<*xi32> to memref<?xi32>
// CHECK:           %[[INDEX_CAST_0:.*]] = arith.index_cast %[[ARG1]] : i32 to index
// CHECK:           %[[GENERIC_ATOMIC_RMW_0:.*]] = memref.generic_atomic_rmw %[[CAST_0]]{{\[}}%[[INDEX_CAST_0]]] : memref<?xi32> {
// CHECK:           ^bb0(%[[VAL_0:.*]]: i32):
// CHECK:             %[[CMPI_0:.*]] = arith.cmpi eq, %[[VAL_0]], %[[ARG2]] : i32
// CHECK:             %[[SELECT_0:.*]] = arith.select %[[CMPI_0]], %[[ARG3]], %[[VAL_0]] : i32
// CHECK:             memref.atomic_yield %[[SELECT_0]] : i32
// CHECK:           }
// CHECK:           tt.return
// CHECK:         }
  tt.func @atomic_cas_scalar(%ptr: !tt.ptr<i32>, %off: i32, %cmp: i32, %val: i32) {
    %ptr_i = tta.make_addr %ptr to sizes: [1], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <i32> to !tta.addr<i32, 1, 1>
    %r = "tta.atomic_cas"(%ptr_i, %off, %cmp, %val) : (!tta.addr<i32, 1, 1>, i32, i32, i32) -> i32
    %u = arith.addi %r, %val : i32
    tt.return
  }
}

// -----

module {
// CHECK-LABEL:   tt.func @atomic_cas_float(
// CHECK-SAME:      %[[ARG0:[-0-9A-Za-z$._]+]]: !tt.ptr<f32>,
// CHECK-SAME:      %[[ARG1:[-0-9A-Za-z$._]+]]: i32,
// CHECK-SAME:      %[[ARG2:[-0-9A-Za-z$._]+]]: f32,
// CHECK-SAME:      %[[ARG3:[-0-9A-Za-z$._]+]]: f32) {
// CHECK:           %[[UNREALIZED_CONVERSION_CAST_0:.*]] = builtin.unrealized_conversion_cast %[[ARG0]] : !tt.ptr<f32> to memref<*xf32>
// CHECK:           %[[CAST_0:.*]] = memref.cast %[[UNREALIZED_CONVERSION_CAST_0]] : memref<*xf32> to memref<?xf32>
// CHECK:           %[[INDEX_CAST_0:.*]] = arith.index_cast %[[ARG1]] : i32 to index
// CHECK:           %[[GENERIC_ATOMIC_RMW_0:.*]] = memref.generic_atomic_rmw %[[CAST_0]]{{\[}}%[[INDEX_CAST_0]]] : memref<?xf32> {
// CHECK:           ^bb0(%[[VAL_0:.*]]: f32):
// CHECK:             %[[CMPF_0:.*]] = arith.cmpf oeq, %[[VAL_0]], %[[ARG2]] : f32
// CHECK:             %[[SELECT_0:.*]] = arith.select %[[CMPF_0]], %[[ARG3]], %[[VAL_0]] : f32
// CHECK:             memref.atomic_yield %[[SELECT_0]] : f32
// CHECK:           }
// CHECK:           tt.return
// CHECK:         }
  tt.func @atomic_cas_float(%ptr: !tt.ptr<f32>, %off: i32, %cmp: f32, %val: f32) {
    %ptr_i = tta.make_addr %ptr to sizes: [1], strides: [1], offsets: [0], wrap_boundaries: [0], layout: "strided" : <f32> to !tta.addr<f32, 1, 1>
    %r = "tta.atomic_cas"(%ptr_i, %off, %cmp, %val) : (!tta.addr<f32, 1, 1>, i32, f32, f32) -> f32
    %u = arith.addf %r, %val : f32
    tt.return
  }
}
